version: '3.8'

services:
  db:
    image: postgres:15
    container_name: eventer-local-db
    restart: always
    environment:
      POSTGRES_DB: eventer_db
      POSTGRES_USER: eventer
      POSTGRES_PASSWORD: eventer_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
