package handler

import (
	"eventer-map-backend/internal/service"
)

// Server implements the ServerInterface generated by oapi-codegen
type Server struct {
	// Embedding ServerInterface allows us to build and run without 
	// fully implementing all methods immediately. 
	// Unimplemented methods will panic if called at runtime.
	ServerInterface 
	services *service.Services
}

// NewServer creates a new API handler
func NewServer(services *service.Services) *Server {
	return &Server{
		services: services,
	}
}
