//go:build go1.22

// Package handler provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package handler

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for ArtistGender.
const (
	ArtistGenderFEMALE ArtistGender = "FEMALE"
	ArtistGenderMALE   ArtistGender = "MALE"
	ArtistGenderMIXED  ArtistGender = "MIXED"
	ArtistGenderOTHER  ArtistGender = "OTHER"
)

// Valid indicates whether the value is a known member of the ArtistGender enum.
func (e ArtistGender) Valid() bool {
	switch e {
	case ArtistGenderFEMALE:
		return true
	case ArtistGenderMALE:
		return true
	case ArtistGenderMIXED:
		return true
	case ArtistGenderOTHER:
		return true
	default:
		return false
	}
}

// Defines values for ArtistStatus.
const (
	ArtistStatusAPPROVED ArtistStatus = "APPROVED"
	ArtistStatusPENDING  ArtistStatus = "PENDING"
	ArtistStatusREJECTED ArtistStatus = "REJECTED"
)

// Valid indicates whether the value is a known member of the ArtistStatus enum.
func (e ArtistStatus) Valid() bool {
	switch e {
	case ArtistStatusAPPROVED:
		return true
	case ArtistStatusPENDING:
		return true
	case ArtistStatusREJECTED:
		return true
	default:
		return false
	}
}

// Defines values for ArtistInputGender.
const (
	ArtistInputGenderFEMALE ArtistInputGender = "FEMALE"
	ArtistInputGenderMALE   ArtistInputGender = "MALE"
	ArtistInputGenderMIXED  ArtistInputGender = "MIXED"
	ArtistInputGenderOTHER  ArtistInputGender = "OTHER"
)

// Valid indicates whether the value is a known member of the ArtistInputGender enum.
func (e ArtistInputGender) Valid() bool {
	switch e {
	case ArtistInputGenderFEMALE:
		return true
	case ArtistInputGenderMALE:
		return true
	case ArtistInputGenderMIXED:
		return true
	case ArtistInputGenderOTHER:
		return true
	default:
		return false
	}
}

// Defines values for ArtistSummaryStatus.
const (
	ArtistSummaryStatusAPPROVED ArtistSummaryStatus = "APPROVED"
	ArtistSummaryStatusPENDING  ArtistSummaryStatus = "PENDING"
	ArtistSummaryStatusREJECTED ArtistSummaryStatus = "REJECTED"
)

// Valid indicates whether the value is a known member of the ArtistSummaryStatus enum.
func (e ArtistSummaryStatus) Valid() bool {
	switch e {
	case ArtistSummaryStatusAPPROVED:
		return true
	case ArtistSummaryStatusPENDING:
		return true
	case ArtistSummaryStatusREJECTED:
		return true
	default:
		return false
	}
}

// Defines values for EventStatus.
const (
	EventStatusAPPROVED EventStatus = "APPROVED"
	EventStatusPENDING  EventStatus = "PENDING"
	EventStatusREJECTED EventStatus = "REJECTED"
)

// Valid indicates whether the value is a known member of the EventStatus enum.
func (e EventStatus) Valid() bool {
	switch e {
	case EventStatusAPPROVED:
		return true
	case EventStatusPENDING:
		return true
	case EventStatusREJECTED:
		return true
	default:
		return false
	}
}

// Defines values for EventHistorySummaryStatus.
const (
	ACTIVE   EventHistorySummaryStatus = "ACTIVE"
	REVERTED EventHistorySummaryStatus = "REVERTED"
)

// Valid indicates whether the value is a known member of the EventHistorySummaryStatus enum.
func (e EventHistorySummaryStatus) Valid() bool {
	switch e {
	case ACTIVE:
		return true
	case REVERTED:
		return true
	default:
		return false
	}
}

// Defines values for EventSummaryStatus.
const (
	EventSummaryStatusAPPROVED EventSummaryStatus = "APPROVED"
	EventSummaryStatusPENDING  EventSummaryStatus = "PENDING"
	EventSummaryStatusREJECTED EventSummaryStatus = "REJECTED"
)

// Valid indicates whether the value is a known member of the EventSummaryStatus enum.
func (e EventSummaryStatus) Valid() bool {
	switch e {
	case EventSummaryStatusAPPROVED:
		return true
	case EventSummaryStatusPENDING:
		return true
	case EventSummaryStatusREJECTED:
		return true
	default:
		return false
	}
}

// Defines values for UserEventActionStatus.
const (
	UserEventActionStatusN1 UserEventActionStatus = 1
	UserEventActionStatusN2 UserEventActionStatus = 2
)

// Valid indicates whether the value is a known member of the UserEventActionStatus enum.
func (e UserEventActionStatus) Valid() bool {
	switch e {
	case UserEventActionStatusN1:
		return true
	case UserEventActionStatusN2:
		return true
	default:
		return false
	}
}

// Defines values for VenueStatus.
const (
	VenueStatusAPPROVED VenueStatus = "APPROVED"
	VenueStatusPENDING  VenueStatus = "PENDING"
	VenueStatusREJECTED VenueStatus = "REJECTED"
)

// Valid indicates whether the value is a known member of the VenueStatus enum.
func (e VenueStatus) Valid() bool {
	switch e {
	case VenueStatusAPPROVED:
		return true
	case VenueStatusPENDING:
		return true
	case VenueStatusREJECTED:
		return true
	default:
		return false
	}
}

// Defines values for VenueSummaryStatus.
const (
	VenueSummaryStatusAPPROVED VenueSummaryStatus = "APPROVED"
	VenueSummaryStatusPENDING  VenueSummaryStatus = "PENDING"
	VenueSummaryStatusREJECTED VenueSummaryStatus = "REJECTED"
)

// Valid indicates whether the value is a known member of the VenueSummaryStatus enum.
func (e VenueSummaryStatus) Valid() bool {
	switch e {
	case VenueSummaryStatusAPPROVED:
		return true
	case VenueSummaryStatusPENDING:
		return true
	case VenueSummaryStatusREJECTED:
		return true
	default:
		return false
	}
}

// Defines values for GetArtistsParamsStatus.
const (
	GetArtistsParamsStatusAPPROVED GetArtistsParamsStatus = "APPROVED"
	GetArtistsParamsStatusPENDING  GetArtistsParamsStatus = "PENDING"
	GetArtistsParamsStatusREJECTED GetArtistsParamsStatus = "REJECTED"
)

// Valid indicates whether the value is a known member of the GetArtistsParamsStatus enum.
func (e GetArtistsParamsStatus) Valid() bool {
	switch e {
	case GetArtistsParamsStatusAPPROVED:
		return true
	case GetArtistsParamsStatusPENDING:
		return true
	case GetArtistsParamsStatusREJECTED:
		return true
	default:
		return false
	}
}

// Defines values for GetEventsParamsTimeRange.
const (
	Past     GetEventsParamsTimeRange = "past"
	Upcoming GetEventsParamsTimeRange = "upcoming"
)

// Valid indicates whether the value is a known member of the GetEventsParamsTimeRange enum.
func (e GetEventsParamsTimeRange) Valid() bool {
	switch e {
	case Past:
		return true
	case Upcoming:
		return true
	default:
		return false
	}
}

// Defines values for GetEventsParamsStatus.
const (
	GetEventsParamsStatusAPPROVED GetEventsParamsStatus = "APPROVED"
	GetEventsParamsStatusPENDING  GetEventsParamsStatus = "PENDING"
	GetEventsParamsStatusREJECTED GetEventsParamsStatus = "REJECTED"
)

// Valid indicates whether the value is a known member of the GetEventsParamsStatus enum.
func (e GetEventsParamsStatus) Valid() bool {
	switch e {
	case GetEventsParamsStatusAPPROVED:
		return true
	case GetEventsParamsStatusPENDING:
		return true
	case GetEventsParamsStatusREJECTED:
		return true
	default:
		return false
	}
}

// Defines values for PutEventsEventIdActionJSONBodyStatus.
const (
	PutEventsEventIdActionJSONBodyStatusN0 PutEventsEventIdActionJSONBodyStatus = 0
	PutEventsEventIdActionJSONBodyStatusN1 PutEventsEventIdActionJSONBodyStatus = 1
	PutEventsEventIdActionJSONBodyStatusN2 PutEventsEventIdActionJSONBodyStatus = 2
)

// Valid indicates whether the value is a known member of the PutEventsEventIdActionJSONBodyStatus enum.
func (e PutEventsEventIdActionJSONBodyStatus) Valid() bool {
	switch e {
	case PutEventsEventIdActionJSONBodyStatusN0:
		return true
	case PutEventsEventIdActionJSONBodyStatusN1:
		return true
	case PutEventsEventIdActionJSONBodyStatusN2:
		return true
	default:
		return false
	}
}

// Defines values for GetVenuesParamsStatus.
const (
	GetVenuesParamsStatusAPPROVED GetVenuesParamsStatus = "APPROVED"
	GetVenuesParamsStatusPENDING  GetVenuesParamsStatus = "PENDING"
	GetVenuesParamsStatusREJECTED GetVenuesParamsStatus = "REJECTED"
)

// Valid indicates whether the value is a known member of the GetVenuesParamsStatus enum.
func (e GetVenuesParamsStatus) Valid() bool {
	switch e {
	case GetVenuesParamsStatusAPPROVED:
		return true
	case GetVenuesParamsStatusPENDING:
		return true
	case GetVenuesParamsStatusREJECTED:
		return true
	default:
		return false
	}
}

// Artist defines model for Artist.
type Artist struct {
	// AuthorId 등록한 유저 ID
	AuthorId *openapi_types.UUID `json:"authorId,omitempty"`

	// BirthDate 생년월일 (YYYY-MM-DD)
	BirthDate *openapi_types.Date `json:"birthDate,omitempty"`

	// DebutDate 데뷔일 (YYYY-MM-DD)
	DebutDate *openapi_types.Date `json:"debutDate,omitempty"`

	// Gender 성별
	Gender *ArtistGender `json:"gender,omitempty"`

	// Hiragana 히라가나
	Hiragana *string `json:"hiragana,omitempty"`

	// Id 아티스트 고유 식별자
	Id *openapi_types.UUID `json:"id,omitempty"`

	// OfficialName 공식 이름
	OfficialName *string `json:"officialName,omitempty"`

	// ProfileImageUrl 프로필 이미지 URL
	ProfileImageUrl *string `json:"profileImageUrl,omitempty"`

	// Status 아티스트 상태 (유저 등록 시 PENDING, 관리자 승인 시 APPROVED)
	Status *ArtistStatus `json:"status,omitempty"`
}

// ArtistGender 성별
type ArtistGender string

// ArtistStatus 아티스트 상태 (유저 등록 시 PENDING, 관리자 승인 시 APPROVED)
type ArtistStatus string

// ArtistInput defines model for ArtistInput.
type ArtistInput struct {
	// BirthDate 생년월일 (YYYY-MM-DD)
	BirthDate *openapi_types.Date `json:"birthDate,omitempty"`

	// DebutDate 데뷔일 (YYYY-MM-DD)
	DebutDate *openapi_types.Date `json:"debutDate,omitempty"`

	// Gender 성별
	Gender ArtistInputGender `json:"gender"`

	// Hiragana 히라가나
	Hiragana *string `json:"hiragana,omitempty"`

	// OfficialName 공식 이름
	OfficialName string `json:"officialName"`

	// ProfileImage 프로필 이미지 업로드 파일 (최대 5MB, JPG/PNG 형식만 허용)
	ProfileImage *openapi_types.File `json:"profileImage,omitempty"`
}

// ArtistInputGender 성별
type ArtistInputGender string

// ArtistSummary defines model for ArtistSummary.
type ArtistSummary struct {
	// Hiragana 히라가나
	Hiragana *string `json:"hiragana,omitempty"`

	// Id 아티스트 고유 식별자
	Id *openapi_types.UUID `json:"id,omitempty"`

	// OfficialName 공식 이름
	OfficialName *string `json:"officialName,omitempty"`

	// Status 아티스트 상태
	Status *ArtistSummaryStatus `json:"status,omitempty"`
}

// ArtistSummaryStatus 아티스트 상태
type ArtistSummaryStatus string

// Event defines model for Event.
type Event struct {
	Artists        *[]ArtistSummary    `json:"artists,omitempty"`
	EndTime        *time.Time          `json:"endTime,omitempty"`
	Id             *openapi_types.UUID `json:"id,omitempty"`
	OpeningTime    *time.Time          `json:"openingTime,omitempty"`
	PosterImageUrl *string             `json:"posterImageUrl,omitempty"`
	RatingCount    *int                `json:"ratingCount,omitempty"`
	RatingSum      *float64            `json:"ratingSum,omitempty"`
	RelatedLinks   *[]string           `json:"relatedLinks,omitempty"`
	StartTime      *time.Time          `json:"startTime,omitempty"`
	Status         *EventStatus        `json:"status,omitempty"`
	Title          *string             `json:"title,omitempty"`
	Venue          *VenueSummary       `json:"venue,omitempty"`
}

// EventStatus defines model for Event.Status.
type EventStatus string

// EventHistorySummary defines model for EventHistorySummary.
type EventHistorySummary struct {
	CreatedAt   *time.Time                 `json:"createdAt,omitempty"`
	EditorId    *openapi_types.UUID        `json:"editorId,omitempty"`
	EventId     *openapi_types.UUID        `json:"eventId,omitempty"`
	Id          *openapi_types.UUID        `json:"id,omitempty"`
	ReportCount *int                       `json:"reportCount,omitempty"`
	Status      *EventHistorySummaryStatus `json:"status,omitempty"`
}

// EventHistorySummaryStatus defines model for EventHistorySummary.Status.
type EventHistorySummaryStatus string

// EventInput defines model for EventInput.
type EventInput struct {
	ArtistIds    *[]openapi_types.UUID `json:"artistIds,omitempty"`
	EndTime      time.Time             `json:"endTime"`
	OpeningTime  *time.Time            `json:"openingTime,omitempty"`
	PosterImage  *openapi_types.File   `json:"posterImage,omitempty"`
	RelatedLinks *[]string             `json:"relatedLinks,omitempty"`
	StartTime    time.Time             `json:"startTime"`
	Title        string                `json:"title"`
	VenueId      openapi_types.UUID    `json:"venueId"`
}

// EventListResponse defines model for EventListResponse.
type EventListResponse struct {
	Events  *[]EventSummary `json:"events,omitempty"`
	HasMore *bool           `json:"hasMore,omitempty"`
}

// EventSummary defines model for EventSummary.
type EventSummary struct {
	EndTime        *time.Time          `json:"endTime,omitempty"`
	Id             *openapi_types.UUID `json:"id,omitempty"`
	PosterImageUrl *string             `json:"posterImageUrl,omitempty"`
	Rating         *float64            `json:"rating,omitempty"`
	StartTime      *time.Time          `json:"startTime,omitempty"`
	Status         *EventSummaryStatus `json:"status,omitempty"`
	Title          *string             `json:"title,omitempty"`
	VenueId        *openapi_types.UUID `json:"venueId,omitempty"`
}

// EventSummaryStatus defines model for EventSummary.Status.
type EventSummaryStatus string

// EventThread defines model for EventThread.
type EventThread struct {
	AuthorId       *openapi_types.UUID `json:"authorId,omitempty"`
	Content        *string             `json:"content,omitempty"`
	CreatedAt      *time.Time          `json:"createdAt,omitempty"`
	EventId        *openapi_types.UUID `json:"eventId,omitempty"`
	Id             *openapi_types.UUID `json:"id,omitempty"`
	RecommendCount *int                `json:"recommendCount,omitempty"`
}

// EventThreadInput defines model for EventThreadInput.
type EventThreadInput struct {
	Content string `json:"content"`
}

// GoogleLoginRequest defines model for GoogleLoginRequest.
type GoogleLoginRequest struct {
	// IdToken 클라이언트로부터 전달받은 구글 ID 토큰
	IdToken string `json:"idToken"`
}

// LinkGoogleRequest defines model for LinkGoogleRequest.
type LinkGoogleRequest struct {
	// IdToken 클라이언트로부터 전달받은 구글 ID 토큰
	IdToken string `json:"idToken"`
}

// LocalLoginRequest defines model for LocalLoginRequest.
type LocalLoginRequest struct {
	// Email 사용자의 이메일 주소
	Email openapi_types.Email `json:"email"`

	// Password 사용자의 비밀번호
	Password string `json:"password"`
}

// RatingInput defines model for RatingInput.
type RatingInput struct {
	Score int `json:"score"`
}

// SignupRequest defines model for SignupRequest.
type SignupRequest struct {
	// Email 사용자의 이메일 주소
	Email openapi_types.Email `json:"email"`

	// Nickname 사용자가 선택한 표시 이름(닉네임)
	Nickname string `json:"nickname"`

	// Password 사용자의 비밀번호
	Password string `json:"password"`
}

// TokenResponse defines model for TokenResponse.
type TokenResponse struct {
	// AccessToken 애플리케이션 액세스 토큰 (JWT)
	AccessToken string `json:"accessToken"`
}

// UserEventAction defines model for UserEventAction.
type UserEventAction struct {
	EventId openapi_types.UUID `json:"eventId"`

	// Status 1: 체크(북마크), 2: 참가
	Status UserEventActionStatus `json:"status"`
}

// UserEventActionStatus 1: 체크(북마크), 2: 참가
type UserEventActionStatus int

// UserProfile defines model for UserProfile.
type UserProfile struct {
	// CreatedAt 가입일시
	CreatedAt *time.Time `json:"createdAt,omitempty"`

	// DisplayName 표시 이름 (닉네임)
	DisplayName *string `json:"displayName,omitempty"`

	// Email 사용자 이메일
	Email *openapi_types.Email `json:"email,omitempty"`

	// Id 사용자 고유 식별자
	Id *openapi_types.UUID `json:"id,omitempty"`
}

// Venue defines model for Venue.
type Venue struct {
	Address  *string `json:"address,omitempty"`
	Capacity *int    `json:"capacity,omitempty"`

	// GoogleMapId Google Maps Place ID
	GoogleMapId  *string             `json:"googleMapId,omitempty"`
	Id           *openapi_types.UUID `json:"id,omitempty"`
	Latitude     *float64            `json:"latitude,omitempty"`
	Longitude    *float64            `json:"longitude,omitempty"`
	OfficialName *string             `json:"officialName,omitempty"`
	Rating       *float64            `json:"rating,omitempty"`
	RatingCount  *int                `json:"ratingCount,omitempty"`
	RelatedLinks *[]string           `json:"relatedLinks,omitempty"`
	Status       *VenueStatus        `json:"status,omitempty"`
}

// VenueStatus defines model for Venue.Status.
type VenueStatus string

// VenueInput defines model for VenueInput.
type VenueInput struct {
	Address      *string   `json:"address,omitempty"`
	Capacity     *int      `json:"capacity,omitempty"`
	GoogleMapId  *string   `json:"googleMapId,omitempty"`
	Latitude     float64   `json:"latitude"`
	Longitude    float64   `json:"longitude"`
	OfficialName string    `json:"officialName"`
	RelatedLinks *[]string `json:"relatedLinks,omitempty"`
}

// VenueListResponse defines model for VenueListResponse.
type VenueListResponse struct {
	// HasMore 결과가 최대치(100개)를 초과하여 더 존재하는지 여부
	HasMore *bool           `json:"hasMore,omitempty"`
	Venues  *[]VenueSummary `json:"venues,omitempty"`
}

// VenueSummary defines model for VenueSummary.
type VenueSummary struct {
	// Id 공연장 고유 식별자
	Id *openapi_types.UUID `json:"id,omitempty"`

	// Latitude 위도
	Latitude *float64 `json:"latitude,omitempty"`

	// Longitude 경도
	Longitude *float64 `json:"longitude,omitempty"`

	// OfficialName 공식 이름
	OfficialName *string `json:"officialName,omitempty"`

	// Rating 런닝 토탈 방식의 평균 평점
	Rating *float64 `json:"rating,omitempty"`

	// Status 공연장 승인 상태
	Status *VenueSummaryStatus `json:"status,omitempty"`
}

// VenueSummaryStatus 공연장 승인 상태
type VenueSummaryStatus string

// VerifyEmailRequest defines model for VerifyEmailRequest.
type VerifyEmailRequest struct {
	// Code 이메일로 수신한 6자리 인증 코드
	Code string `json:"code"`

	// Email 인증할 사용자의 이메일 주소
	Email openapi_types.Email `json:"email"`
}

// GetArtistsParams defines parameters for GetArtists.
type GetArtistsParams struct {
	// Query 검색어 (초성, 영문, 히라가나 등)
	Query *string `form:"query,omitempty" json:"query,omitempty"`

	// Status 특정 상태의 아티스트만 필터링 (선택)
	Status *GetArtistsParamsStatus `form:"status,omitempty" json:"status,omitempty"`
}

// GetArtistsParamsStatus defines parameters for GetArtists.
type GetArtistsParamsStatus string

// PostAuthLogoutParams defines parameters for PostAuthLogout.
type PostAuthLogoutParams struct {
	// RefreshToken 무효화할 리프레시 토큰
	RefreshToken string `form:"refreshToken" json:"refreshToken"`
}

// PostAuthRefreshParams defines parameters for PostAuthRefresh.
type PostAuthRefreshParams struct {
	// RefreshToken HttpOnly 리프레시 토큰
	RefreshToken string `form:"refreshToken" json:"refreshToken"`
}

// GetEventsParams defines parameters for GetEvents.
type GetEventsParams struct {
	ArtistId  *openapi_types.UUID       `form:"artistId,omitempty" json:"artistId,omitempty"`
	VenueId   *openapi_types.UUID       `form:"venueId,omitempty" json:"venueId,omitempty"`
	TimeRange *GetEventsParamsTimeRange `form:"timeRange,omitempty" json:"timeRange,omitempty"`
	Status    *GetEventsParamsStatus    `form:"status,omitempty" json:"status,omitempty"`
}

// GetEventsParamsTimeRange defines parameters for GetEvents.
type GetEventsParamsTimeRange string

// GetEventsParamsStatus defines parameters for GetEvents.
type GetEventsParamsStatus string

// PutEventsEventIdActionJSONBody defines parameters for PutEventsEventIdAction.
type PutEventsEventIdActionJSONBody struct {
	// Status 0: 없음, 1: 체크(북마크), 2: 참가
	Status PutEventsEventIdActionJSONBodyStatus `json:"status"`
}

// PutEventsEventIdActionJSONBodyStatus defines parameters for PutEventsEventIdAction.
type PutEventsEventIdActionJSONBodyStatus int

// GetVenuesParams defines parameters for GetVenues.
type GetVenuesParams struct {
	// MinLat 최소 위도 (남쪽 경계)
	MinLat float64 `form:"minLat" json:"minLat"`

	// MaxLat 최대 위도 (북쪽 경계)
	MaxLat float64 `form:"maxLat" json:"maxLat"`

	// MinLng 최소 경도 (서쪽 경계)
	MinLng float64 `form:"minLng" json:"minLng"`

	// MaxLng 최대 경도 (동쪽 경계)
	MaxLng float64 `form:"maxLng" json:"maxLng"`

	// Query 공연장 이름 검색어 (선택)
	Query *string `form:"query,omitempty" json:"query,omitempty"`

	// Status 상태 필터링 (선택)
	Status *GetVenuesParamsStatus `form:"status,omitempty" json:"status,omitempty"`
}

// GetVenuesParamsStatus defines parameters for GetVenues.
type GetVenuesParamsStatus string

// PostArtistsMultipartRequestBody defines body for PostArtists for multipart/form-data ContentType.
type PostArtistsMultipartRequestBody = ArtistInput

// PutArtistsArtistIdMultipartRequestBody defines body for PutArtistsArtistId for multipart/form-data ContentType.
type PutArtistsArtistIdMultipartRequestBody = ArtistInput

// PostAuthGoogleJSONRequestBody defines body for PostAuthGoogle for application/json ContentType.
type PostAuthGoogleJSONRequestBody = GoogleLoginRequest

// PostAuthLoginJSONRequestBody defines body for PostAuthLogin for application/json ContentType.
type PostAuthLoginJSONRequestBody = LocalLoginRequest

// PostAuthSignupJSONRequestBody defines body for PostAuthSignup for application/json ContentType.
type PostAuthSignupJSONRequestBody = SignupRequest

// PostAuthSignupVerifyJSONRequestBody defines body for PostAuthSignupVerify for application/json ContentType.
type PostAuthSignupVerifyJSONRequestBody = VerifyEmailRequest

// PostEventsMultipartRequestBody defines body for PostEvents for multipart/form-data ContentType.
type PostEventsMultipartRequestBody = EventInput

// PutEventsEventIdMultipartRequestBody defines body for PutEventsEventId for multipart/form-data ContentType.
type PutEventsEventIdMultipartRequestBody = EventInput

// PutEventsEventIdActionJSONRequestBody defines body for PutEventsEventIdAction for application/json ContentType.
type PutEventsEventIdActionJSONRequestBody PutEventsEventIdActionJSONBody

// PostEventsEventIdRateJSONRequestBody defines body for PostEventsEventIdRate for application/json ContentType.
type PostEventsEventIdRateJSONRequestBody = RatingInput

// PostEventsEventIdThreadsJSONRequestBody defines body for PostEventsEventIdThreads for application/json ContentType.
type PostEventsEventIdThreadsJSONRequestBody = EventThreadInput

// PostUsersMeLinkGoogleJSONRequestBody defines body for PostUsersMeLinkGoogle for application/json ContentType.
type PostUsersMeLinkGoogleJSONRequestBody = LinkGoogleRequest

// PostVenuesJSONRequestBody defines body for PostVenues for application/json ContentType.
type PostVenuesJSONRequestBody = VenueInput

// PutVenuesVenueIdJSONRequestBody defines body for PutVenuesVenueId for application/json ContentType.
type PutVenuesVenueIdJSONRequestBody = VenueInput

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// GetArtists 아티스트 목록 조회 (통합)
	// (GET /artists)
	GetArtists(w http.ResponseWriter, r *http.Request, params GetArtistsParams)
	// PostArtists 아티스트 등록
	// (POST /artists)
	PostArtists(w http.ResponseWriter, r *http.Request)
	// DeleteArtistsArtistId 아티스트 삭제
	// (DELETE /artists/{artistId})
	DeleteArtistsArtistId(w http.ResponseWriter, r *http.Request, artistId openapi_types.UUID)
	// GetArtistsArtistId 아티스트 상세 정보 조회
	// (GET /artists/{artistId})
	GetArtistsArtistId(w http.ResponseWriter, r *http.Request, artistId openapi_types.UUID)
	// PutArtistsArtistId 아티스트 수정
	// (PUT /artists/{artistId})
	PutArtistsArtistId(w http.ResponseWriter, r *http.Request, artistId openapi_types.UUID)
	// PostArtistsArtistIdApprove 아티스트 승인 (관리자 전용)
	// (POST /artists/{artistId}/approve)
	PostArtistsArtistIdApprove(w http.ResponseWriter, r *http.Request, artistId openapi_types.UUID)
	// PostAuthGoogle 구글 로그인
	// (POST /auth/google)
	PostAuthGoogle(w http.ResponseWriter, r *http.Request)
	// PostAuthLogin 로컬 로그인
	// (POST /auth/login)
	PostAuthLogin(w http.ResponseWriter, r *http.Request)
	// PostAuthLogout 로그아웃
	// (POST /auth/logout)
	PostAuthLogout(w http.ResponseWriter, r *http.Request, params PostAuthLogoutParams)
	// PostAuthRefresh 액세스 토큰 갱신
	// (POST /auth/refresh)
	PostAuthRefresh(w http.ResponseWriter, r *http.Request, params PostAuthRefreshParams)
	// PostAuthSignup 로컬 회원가입
	// (POST /auth/signup)
	PostAuthSignup(w http.ResponseWriter, r *http.Request)
	// PostAuthSignupVerify 이메일 인증
	// (POST /auth/signup/verify)
	PostAuthSignupVerify(w http.ResponseWriter, r *http.Request)
	// PostEventHistoryHistoryIdReport 수정 이력 신고
	// (POST /event-history/{historyId}/report)
	PostEventHistoryHistoryIdReport(w http.ResponseWriter, r *http.Request, historyId openapi_types.UUID)
	// PostEventThreadsThreadIdRecommend 스레드 추천 토글
	// (POST /event-threads/{threadId}/recommend)
	PostEventThreadsThreadIdRecommend(w http.ResponseWriter, r *http.Request, threadId openapi_types.UUID)
	// GetEvents 이벤트 목록 조회
	// (GET /events)
	GetEvents(w http.ResponseWriter, r *http.Request, params GetEventsParams)
	// PostEvents 이벤트 등록 (위키 방식)
	// (POST /events)
	PostEvents(w http.ResponseWriter, r *http.Request)
	// GetEventsEventId 이벤트 상세 조회
	// (GET /events/{eventId})
	GetEventsEventId(w http.ResponseWriter, r *http.Request, eventId openapi_types.UUID)
	// PutEventsEventId 이벤트 수정 (위키 방식)
	// (PUT /events/{eventId})
	PutEventsEventId(w http.ResponseWriter, r *http.Request, eventId openapi_types.UUID)
	// PutEventsEventIdAction 이벤트 액션(상태) 변경
	// (PUT /events/{eventId}/action)
	PutEventsEventIdAction(w http.ResponseWriter, r *http.Request, eventId openapi_types.UUID)
	// PostEventsEventIdDeleteRequest 이벤트 삭제 요청
	// (POST /events/{eventId}/delete-request)
	PostEventsEventIdDeleteRequest(w http.ResponseWriter, r *http.Request, eventId openapi_types.UUID)
	// GetEventsEventIdHistory 이벤트 수정 이력 조회
	// (GET /events/{eventId}/history)
	GetEventsEventIdHistory(w http.ResponseWriter, r *http.Request, eventId openapi_types.UUID)
	// PostEventsEventIdRate 이벤트 평점 등록
	// (POST /events/{eventId}/rate)
	PostEventsEventIdRate(w http.ResponseWriter, r *http.Request, eventId openapi_types.UUID)
	// GetEventsEventIdThreads 이벤트 스레드(부가정보) 조회
	// (GET /events/{eventId}/threads)
	GetEventsEventIdThreads(w http.ResponseWriter, r *http.Request, eventId openapi_types.UUID)
	// PostEventsEventIdThreads 이벤트 스레드 작성
	// (POST /events/{eventId}/threads)
	PostEventsEventIdThreads(w http.ResponseWriter, r *http.Request, eventId openapi_types.UUID)
	// GetPing 서버 상태 확인
	// (GET /ping)
	GetPing(w http.ResponseWriter, r *http.Request)
	// GetUsersMe 현재 사용자 프로필 조회
	// (GET /users/me)
	GetUsersMe(w http.ResponseWriter, r *http.Request)
	// GetUsersMeEvents 내 이벤트 액션(참가/체크) 목록 조회
	// (GET /users/me/events)
	GetUsersMeEvents(w http.ResponseWriter, r *http.Request)
	// PostUsersMeLinkGoogle 구글 계정 연동
	// (POST /users/me/link-google)
	PostUsersMeLinkGoogle(w http.ResponseWriter, r *http.Request)
	// GetVenues 공연장 목록 조회 (지도 기반)
	// (GET /venues)
	GetVenues(w http.ResponseWriter, r *http.Request, params GetVenuesParams)
	// PostVenues 공연장 등록
	// (POST /venues)
	PostVenues(w http.ResponseWriter, r *http.Request)
	// DeleteVenuesVenueId 공연장 삭제
	// (DELETE /venues/{venueId})
	DeleteVenuesVenueId(w http.ResponseWriter, r *http.Request, venueId openapi_types.UUID)
	// GetVenuesVenueId 공연장 상세 정보 조회
	// (GET /venues/{venueId})
	GetVenuesVenueId(w http.ResponseWriter, r *http.Request, venueId openapi_types.UUID)
	// PutVenuesVenueId 공연장 수정
	// (PUT /venues/{venueId})
	PutVenuesVenueId(w http.ResponseWriter, r *http.Request, venueId openapi_types.UUID)
	// PostVenuesVenueIdApprove 공연장 승인 (관리자 전용)
	// (POST /venues/{venueId}/approve)
	PostVenuesVenueIdApprove(w http.ResponseWriter, r *http.Request, venueId openapi_types.UUID)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetArtists operation middleware
func (siw *ServerInterfaceWrapper) GetArtists(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params GetArtistsParams

	// ------------- Optional query parameter "query" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "query", r.URL.Query(), &params.Query, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "query"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "query", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "status", r.URL.Query(), &params.Status, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "status"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "status", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetArtists(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostArtists operation middleware
func (siw *ServerInterfaceWrapper) PostArtists(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostArtists(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteArtistsArtistId operation middleware
func (siw *ServerInterfaceWrapper) DeleteArtistsArtistId(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "artistId" -------------
	var artistId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "artistId", r.PathValue("artistId"), &artistId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "artistId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteArtistsArtistId(w, r, artistId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetArtistsArtistId operation middleware
func (siw *ServerInterfaceWrapper) GetArtistsArtistId(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "artistId" -------------
	var artistId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "artistId", r.PathValue("artistId"), &artistId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "artistId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetArtistsArtistId(w, r, artistId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PutArtistsArtistId operation middleware
func (siw *ServerInterfaceWrapper) PutArtistsArtistId(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "artistId" -------------
	var artistId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "artistId", r.PathValue("artistId"), &artistId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "artistId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PutArtistsArtistId(w, r, artistId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostArtistsArtistIdApprove operation middleware
func (siw *ServerInterfaceWrapper) PostArtistsArtistIdApprove(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "artistId" -------------
	var artistId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "artistId", r.PathValue("artistId"), &artistId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "artistId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostArtistsArtistIdApprove(w, r, artistId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostAuthGoogle operation middleware
func (siw *ServerInterfaceWrapper) PostAuthGoogle(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostAuthGoogle(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostAuthLogin operation middleware
func (siw *ServerInterfaceWrapper) PostAuthLogin(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostAuthLogin(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostAuthLogout operation middleware
func (siw *ServerInterfaceWrapper) PostAuthLogout(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params PostAuthLogoutParams

	{
		var cookie *http.Cookie

		if cookie, err = r.Cookie("refreshToken"); err == nil {
			var value string
			err = runtime.BindStyledParameterWithOptions("simple", "refreshToken", cookie.Value, &value, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationCookie, Explode: true, Required: true, Type: "string", Format: ""})
			if err != nil {
				siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "refreshToken", Err: err})
				return
			}
			params.RefreshToken = value

		} else {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "refreshToken"})
			return
		}
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostAuthLogout(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostAuthRefresh operation middleware
func (siw *ServerInterfaceWrapper) PostAuthRefresh(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params PostAuthRefreshParams

	{
		var cookie *http.Cookie

		if cookie, err = r.Cookie("refreshToken"); err == nil {
			var value string
			err = runtime.BindStyledParameterWithOptions("simple", "refreshToken", cookie.Value, &value, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationCookie, Explode: true, Required: true, Type: "string", Format: ""})
			if err != nil {
				siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "refreshToken", Err: err})
				return
			}
			params.RefreshToken = value

		} else {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "refreshToken"})
			return
		}
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostAuthRefresh(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostAuthSignup operation middleware
func (siw *ServerInterfaceWrapper) PostAuthSignup(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostAuthSignup(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostAuthSignupVerify operation middleware
func (siw *ServerInterfaceWrapper) PostAuthSignupVerify(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostAuthSignupVerify(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostEventHistoryHistoryIdReport operation middleware
func (siw *ServerInterfaceWrapper) PostEventHistoryHistoryIdReport(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "historyId" -------------
	var historyId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "historyId", r.PathValue("historyId"), &historyId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "historyId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostEventHistoryHistoryIdReport(w, r, historyId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostEventThreadsThreadIdRecommend operation middleware
func (siw *ServerInterfaceWrapper) PostEventThreadsThreadIdRecommend(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "threadId" -------------
	var threadId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "threadId", r.PathValue("threadId"), &threadId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "threadId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostEventThreadsThreadIdRecommend(w, r, threadId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetEvents operation middleware
func (siw *ServerInterfaceWrapper) GetEvents(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params GetEventsParams

	// ------------- Optional query parameter "artistId" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "artistId", r.URL.Query(), &params.ArtistId, runtime.BindQueryParameterOptions{Type: "string", Format: "uuid"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "artistId"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "artistId", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "venueId" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "venueId", r.URL.Query(), &params.VenueId, runtime.BindQueryParameterOptions{Type: "string", Format: "uuid"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "venueId"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "venueId", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "timeRange" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "timeRange", r.URL.Query(), &params.TimeRange, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "timeRange"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "timeRange", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "status", r.URL.Query(), &params.Status, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "status"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "status", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetEvents(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostEvents operation middleware
func (siw *ServerInterfaceWrapper) PostEvents(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostEvents(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetEventsEventId operation middleware
func (siw *ServerInterfaceWrapper) GetEventsEventId(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "eventId" -------------
	var eventId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "eventId", r.PathValue("eventId"), &eventId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "eventId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetEventsEventId(w, r, eventId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PutEventsEventId operation middleware
func (siw *ServerInterfaceWrapper) PutEventsEventId(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "eventId" -------------
	var eventId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "eventId", r.PathValue("eventId"), &eventId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "eventId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PutEventsEventId(w, r, eventId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PutEventsEventIdAction operation middleware
func (siw *ServerInterfaceWrapper) PutEventsEventIdAction(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "eventId" -------------
	var eventId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "eventId", r.PathValue("eventId"), &eventId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "eventId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PutEventsEventIdAction(w, r, eventId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostEventsEventIdDeleteRequest operation middleware
func (siw *ServerInterfaceWrapper) PostEventsEventIdDeleteRequest(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "eventId" -------------
	var eventId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "eventId", r.PathValue("eventId"), &eventId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "eventId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostEventsEventIdDeleteRequest(w, r, eventId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetEventsEventIdHistory operation middleware
func (siw *ServerInterfaceWrapper) GetEventsEventIdHistory(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "eventId" -------------
	var eventId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "eventId", r.PathValue("eventId"), &eventId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "eventId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetEventsEventIdHistory(w, r, eventId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostEventsEventIdRate operation middleware
func (siw *ServerInterfaceWrapper) PostEventsEventIdRate(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "eventId" -------------
	var eventId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "eventId", r.PathValue("eventId"), &eventId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "eventId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostEventsEventIdRate(w, r, eventId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetEventsEventIdThreads operation middleware
func (siw *ServerInterfaceWrapper) GetEventsEventIdThreads(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "eventId" -------------
	var eventId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "eventId", r.PathValue("eventId"), &eventId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "eventId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetEventsEventIdThreads(w, r, eventId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostEventsEventIdThreads operation middleware
func (siw *ServerInterfaceWrapper) PostEventsEventIdThreads(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "eventId" -------------
	var eventId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "eventId", r.PathValue("eventId"), &eventId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "eventId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostEventsEventIdThreads(w, r, eventId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetPing operation middleware
func (siw *ServerInterfaceWrapper) GetPing(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetPing(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetUsersMe operation middleware
func (siw *ServerInterfaceWrapper) GetUsersMe(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetUsersMe(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetUsersMeEvents operation middleware
func (siw *ServerInterfaceWrapper) GetUsersMeEvents(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetUsersMeEvents(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostUsersMeLinkGoogle operation middleware
func (siw *ServerInterfaceWrapper) PostUsersMeLinkGoogle(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostUsersMeLinkGoogle(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetVenues operation middleware
func (siw *ServerInterfaceWrapper) GetVenues(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params GetVenuesParams

	// ------------- Required query parameter "minLat" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "minLat", r.URL.Query(), &params.MinLat, runtime.BindQueryParameterOptions{Type: "number", Format: "double"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "minLat"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "minLat", Err: err})
		}
		return
	}

	// ------------- Required query parameter "maxLat" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "maxLat", r.URL.Query(), &params.MaxLat, runtime.BindQueryParameterOptions{Type: "number", Format: "double"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "maxLat"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "maxLat", Err: err})
		}
		return
	}

	// ------------- Required query parameter "minLng" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "minLng", r.URL.Query(), &params.MinLng, runtime.BindQueryParameterOptions{Type: "number", Format: "double"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "minLng"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "minLng", Err: err})
		}
		return
	}

	// ------------- Required query parameter "maxLng" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "maxLng", r.URL.Query(), &params.MaxLng, runtime.BindQueryParameterOptions{Type: "number", Format: "double"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "maxLng"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "maxLng", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "query" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "query", r.URL.Query(), &params.Query, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "query"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "query", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "status", r.URL.Query(), &params.Status, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "status"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "status", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetVenues(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostVenues operation middleware
func (siw *ServerInterfaceWrapper) PostVenues(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostVenues(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteVenuesVenueId operation middleware
func (siw *ServerInterfaceWrapper) DeleteVenuesVenueId(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "venueId" -------------
	var venueId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "venueId", r.PathValue("venueId"), &venueId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "venueId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteVenuesVenueId(w, r, venueId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetVenuesVenueId operation middleware
func (siw *ServerInterfaceWrapper) GetVenuesVenueId(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "venueId" -------------
	var venueId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "venueId", r.PathValue("venueId"), &venueId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "venueId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetVenuesVenueId(w, r, venueId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PutVenuesVenueId operation middleware
func (siw *ServerInterfaceWrapper) PutVenuesVenueId(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "venueId" -------------
	var venueId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "venueId", r.PathValue("venueId"), &venueId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "venueId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PutVenuesVenueId(w, r, venueId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostVenuesVenueIdApprove operation middleware
func (siw *ServerInterfaceWrapper) PostVenuesVenueIdApprove(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "venueId" -------------
	var venueId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "venueId", r.PathValue("venueId"), &venueId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "venueId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostVenuesVenueIdApprove(w, r, venueId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/ping", wrapper.GetPing)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/auth/google", wrapper.PostAuthGoogle)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/auth/refresh", wrapper.PostAuthRefresh)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/auth/signup", wrapper.PostAuthSignup)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/auth/signup/verify", wrapper.PostAuthSignupVerify)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/auth/login", wrapper.PostAuthLogin)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/users/me", wrapper.GetUsersMe)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/users/me/events", wrapper.GetUsersMeEvents)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/users/me/link-google", wrapper.PostUsersMeLinkGoogle)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/auth/logout", wrapper.PostAuthLogout)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/artists", wrapper.GetArtists)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/artists", wrapper.PostArtists)
	m.HandleFunc(http.MethodDelete+" "+options.BaseURL+"/artists/{artistId}", wrapper.DeleteArtistsArtistId)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/artists/{artistId}", wrapper.GetArtistsArtistId)
	m.HandleFunc(http.MethodPut+" "+options.BaseURL+"/artists/{artistId}", wrapper.PutArtistsArtistId)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/artists/{artistId}/approve", wrapper.PostArtistsArtistIdApprove)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/venues", wrapper.GetVenues)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/venues", wrapper.PostVenues)
	m.HandleFunc(http.MethodDelete+" "+options.BaseURL+"/venues/{venueId}", wrapper.DeleteVenuesVenueId)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/venues/{venueId}", wrapper.GetVenuesVenueId)
	m.HandleFunc(http.MethodPut+" "+options.BaseURL+"/venues/{venueId}", wrapper.PutVenuesVenueId)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/venues/{venueId}/approve", wrapper.PostVenuesVenueIdApprove)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/events", wrapper.GetEvents)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/events", wrapper.PostEvents)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/events/{eventId}", wrapper.GetEventsEventId)
	m.HandleFunc(http.MethodPut+" "+options.BaseURL+"/events/{eventId}", wrapper.PutEventsEventId)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/events/{eventId}/delete-request", wrapper.PostEventsEventIdDeleteRequest)
	m.HandleFunc(http.MethodPut+" "+options.BaseURL+"/events/{eventId}/action", wrapper.PutEventsEventIdAction)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/events/{eventId}/rate", wrapper.PostEventsEventIdRate)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/events/{eventId}/threads", wrapper.GetEventsEventIdThreads)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/events/{eventId}/threads", wrapper.PostEventsEventIdThreads)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/event-threads/{threadId}/recommend", wrapper.PostEventThreadsThreadIdRecommend)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/events/{eventId}/history", wrapper.GetEventsEventIdHistory)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/event-history/{historyId}/report", wrapper.PostEventHistoryHistoryIdReport)

	return m
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7F3rb9tWlv9XLrj7QQKUyGk7C6yB/eDUntRB3BqOm25R5AMj3dicSKRKUd0YgQE5ZgLFUhEHscZKInnl",
	"reM84MHStuIqGGf3/9G9/B8G98GHpEuRlp8p5lMVS7yPc37nfQ77QEpp2ZymQtXIS6MPpHxqHmZl+nFM",
	"N5S8QT7ldC0HdUOB9O9ywZjX9Mk0+ZyG+ZSu5AxFU6VRCT3fRZsNu1oHuN7EzSKYHJcS0l1Nz8qGNCoV",
	"CkpaSkjGQg5Ko1Le0BV1TlpMSHcU3Zgflw3YvyJebqBHJn61hhuHIPbjjz/+eGlq6tL4eNy/bpo8Klg3",
	"De8UDPG66FcL/T7UonNQTUNdcFJzF+2bUkKCaiErjf4kTY3dmJAS0p8n+Iepyf+cIOT4bvabiRnptmDp",
	"eUWX52RV7l/c3iihxmHHKqKHNdGhFAEzcNW0yxZe2bJX2qCz38T1JsDlBto38cZqFLZod+8qKUXOfCtn",
	"BRTs7H/A5QbAjRbaNkWP53TtrpKBk1l5Dn6vZwSXWjPRZt2umnSR/23jN0Xw/cyNrqPpimjpvCEbhXzI",
	"lfHykr1cBzEORYZNgMt1MD3x7fjkt9cSoNMqou0dvLEK8MpH3GjTb8emp2e+uzVB0eDwkj8hJSTnWykh",
	"zUxcn/h6dmJcwMtF9y/anb/AlEEOzcRpUs0VBDL1TxE4rgicIFqjQRWvP0KbdfS8DuxKhZIRf6ijShH8",
	"aepqAlyfvpac/vYasGtVInRvKsBeL+GX77oIfEdRZX1BEsFHhz8XFB2mCRm7ruaS/3Ygxm4Wslmybh/K",
	"/lgK5gha4IRFeeIXqIoMI6U+/agYMEs//KsO70qj0r8kPTOb5DY22c0tbyNZ12X6b6imZxVGmy6hvGQo",
	"WRjMpnDC56CqqHNHWzun5Q2o+9V5mJrWZUNR577WCoxY/HtFNeAc1L0f3CSM8Z9CK9zJ+I6gFrJ3+O9h",
	"RjZg+oai3uumcthJegmbN2TdONr1PbQNi6SEZChGBvpI4X3zC1QLMAwvt8iPXLgEAvMbJW9o+kKgFkjp",
	"kFBxzIh+eZhWDMflC0UXJIeI+NuIgNVhTtONAUjq587Y17OTtyYoR25NzBxRtgOsNBPwyXQQ+AJOf2yx",
	"Pq68dj0UZHTOV7xCRCMSnHrMJlvSW8B/Lo8Jt4MwcEPJGzMwn9PUPOyHAgV5dFVPVxyg6efl/JSm+wlw",
	"R9MyUFYHgDRQwE/LbAxrASJq94uplKMiT8yj2XkdyunBMXQo3VOaasAuzef7bghlfhr6OaVls1BNB6ro",
	"EAoFKNzgm/fIuvNDkTRf07S5DLyhzSnqDPy5AEU5DSU9q92DqsAxXmqhxiFutPBf2/ZKm3j8B0XbtABu",
	"mqi8g6xXuFEEnQ87nXYRTI4D+3HTXrJCdZOzn+i8RP+yM38ex9VScmYwdWFWVgQJAPxwB798hzdWcaNG",
	"/fx3NBzFvx3ixxV/AMGeF2kkOZ//L01Ph6yNPprIKqK9kl1r+9d1Hw+7v3MA9wERIWaosgtAcj7F1XtW",
	"vq9kia76U0LKKir7fCUhEhj/Cdjzom1vKnNqIXf2tFeV1D1VGLm5a3esIsBm016mOUH7WR2X6zygi6Hy",
	"E2Ru4Q0zfqEY67uXiNhUDIK9AjmVgvl8gGziatNeq6DtHXxYJBL6qAZwdRObbbyyxQURxK7/MBsPPbV/",
	"G9Epv89DnSrXsRTbW+i9RDQBQWH2lVGA91r20k4MHSyhNyV7aSeeAF+MAmy1O1bRC7mvJL64HYpv50Tu",
	"fkH3mmaJmpCwpieVYBXxxiPcOMTlem+CK9BMppV8LiMviJMTXVgGIWAOE0FP/iIJnjJIKoZIxIhM8y0n",
	"Hu3Bdzqtw3xe7InIOTmlGAviAG2OGrQpOSeqGzBrB6bkXB5MZ+QUZIWDYb2RjGwoRiENI/qdGU2dO8rv",
	"e9NWx/N6w5MkJxiVHdNZDkRKULx8UnC5eCw+GaYMTvS6l/Rf4HYQDwbHq74As0c37lmd/UNqqWn6Gn+s",
	"xa6MjHSsehy9PgS4VersH9rVGl7fAejXNYA3W3hjx67W0MoaS4PvoIOid1U3buXxU/QYuTu9JSCV+N6B",
	"YbBIT3b2P+B1C2+8Hiph7Uddj/6tm+ip2WVbooGxlxmfIi9zzOy5p6R6ykL/baFyg/ojyyWArHe43CCu",
	"lv30Sef3JvkPbq5GO2GQ5+AxwSm7nUaS/hbUlbsLE8SKBjrHKU3ITMcco806wKUaLjeJ//pveGMVbe8A",
	"3Gjj7QbAn9bQ8/pR7D19zq42wXGd7wAnlt6mXz8QTsBUQVeMhZtE1HjFEco61McKxrz3rz87+17/YZZ4",
	"YvTXRKbpt9455g0jJy2ShRX1rkYVJEuisJAe6sSUg7HpSZp90/PcYbw8cnnESWfKOUUalb68PHL5S+p+",
	"G/P0VElfDWUOily5vSJefoL/2orhVgmbuwDVVtHKGiDcsmoA7bQJWddbTHltPELN1yTorZqgqyyE3r+j",
	"1eCXa7j6CeBmFe23ALJq9ouaRA9IxENTifWRrkFjjJ+KnFSXs9CAel4a/SnwcICfLgFwbQnttBPAX2AD",
	"6PkucRQV8szPBUizsSyUcv/JlCINGBX1BlTnCJ+uCJDQ55mufMTNKhcpii/fvWkdsmrapoXeLIEYi82C",
	"jsLF13+WoeXzNkEss02Ut1+MjPTkd+RcLqOkKNWTf8mzoMXb+CTqaYu0Ht4lkZuW/bICsLnb2f/ABMUx",
	"JpIQLuz3MfvxB7tKS7mGPJen1QYOkNs8TSqyEE3cLMY45eIObt0WhJjbdwA6BxW7WsfrqwCtWYgohq6z",
	"0EaGPpROa3kfTHWm8a5q6YUeOmcLGUPJybqRJFrmUlo25G5Sh1OYeXuL3WrI0AtwsY/LV47E5fCtRVx0",
	"Ojs4FxPSV2xbkfYl6Mcv17qUIhVkvzr86TbBaxAUHPL3s34x4eqv5AOnVrTIjpKBwt4O3pvSgwXqjXVV",
	"sR/+DTfrINaHDFTeQq9bnb0KwHs1tL2DVt/G+6AxTnfn5+QsTPfrMqoDiCb2VIDs/bib036lEBZe9sv+",
	"V6IAlt7Qz8QvBdqf3h/g9ce4UWG/+nfBWutWZ89Cqyw+3yMUpBR1PFfiyvL90EGpYxWPAQe2ToAmEFqw",
	"rscnx6mPsbyEzbZrhspvO7sRrNFF4OTIGch3j5YmTP9qMFmp7bf+DzdM4r65cAnW790MYBsGafeCcQw5",
	"5huUasRGDynO04VzRsDFMC1nAj3GqKNoJRDDtdIoj2yIDkK/WrjRIi4XQSVzUxleKDz4DuU6emrGj6OI",
	"6EJHsEtJOZfTtV9YrkDosqBKsdO2AN56RoO0HgFzIkwewlG8ghjzO8n3jj9DFBzaL3b2PsUHOS0Olsf4",
	"qf7oSo2Tzed6Dsd2tk7M18raNHmfYQASCsZ8kuXXglnfWyEkqpRENyR+rXX2m4BEWXstcP2H2dgYrUYk",
	"wAy8q8P8fBwgq95pPxEzu2DMs2zvQCd1eIoLir1nrE26S0Qi1vP8AWN9QpqHcpqC/IF0ExqXvta0e4rA",
	"V/zGMHLfqZkFgLZ37DUTNUu4XPcKuN7hegG+GOIS4/KWXXlLG6Xtl2+Jf/SGmK0VX6WY7RLvMaH8S7RZ",
	"7/zexo22H3IEuT68ZQhDguHm5kA6+4ddRT2qM2m2xElB+jYTw4vy/pTQ1V/r/ie4IoJro4be/5365Bur",
	"nb13AG830PtHvZBCm3X8952okNJ40UFsvVy7u9fEjRZe2cLrq9isi64I0E6LYP/F2iBYke1CMkDuOna1",
	"GUBLasdSjA+uJdOZ7mQl3UHW7KStV3c+NAvzed4vGJphFQTijGtVE79aPjIC8f837YdbbqQ7Jd+/NDYH",
	"/2MkHgK/Xvi4JxgAHU7tAfqIq0IhWGhY4ddJeLlEcPuy1V/PDzGF3GSGoSpEOi8Woo6lvjjZOtYuLjc/",
	"DxMp2CveF2v2wILdbwBC87Sp5yQMpg+cbo/AoBRiwZhnHUWnZEK725VOwXwGajR4X87maJWiq4JDozB/",
	"xQdZdfx4E63W8HoJr3xA5RIqb12O0jcRbI4H7/SWhZYjAj57ZvPlGt77W8xXLdp6hvY/ODkH19oBVDJR",
	"41OAYbVfVvCrVdYPEwq/5C+0hBYBhf7L+Apl9NYEkfaLKm60ndCB0oRq0Rcm+q3CgRpNYzL4sNreKSFU",
	"UDi8eF6ei4Jz8fdESHUhbpdJKNrZtWip600F/VahEO9WiT03EIORdoVdmmcDLckH/MNkejHJJkIGQHPD",
	"7Oyb+GONdzDQ0U672kLlj1QGm68B/v0tflyJOfMhJG59CtDmFrJ2E84AM7JaXipOCEr/yM03zvlm2Omi",
	"5DDcO51GEqOHJuUmlb9hcg48TcUpRxfysYxfvItrBm3szicfsA+MabxN3M+3AJKyvvA8bw9Pz7iPRiGq",
	"s+UZ0PRgDe/Vh6PpyhZqltDzOuCL2I+bnXbRR1ZOAz9Z/ZXxvsLABPuFmEI91V1f7iw6SRLitXwTNsdd",
	"ylCycEZW56Cw7lzIpbQseZ527BrCTpAHF76YHToo1NXKddS6tVPy6i5a+1DFURJWqna8lT0n4eu83aGG",
	"3rUA3n5CNCqyari2hFZr6J3FtQNutABebmBzd6DKPMUqtW+E74yL1Gww+KRq1AHlBmS1YldlNQ5Q+aP3",
	"rg1aPmK7DFXU9GDDFonhukkCctYBFhfhx1NKyQe8f3sxXD1NuJ3e4Xrc6wq/mPn9QH5HrFmG1ShdpjgF",
	"ykGyLCxMDiumhfPk1oXQCmeBkmHKi0T0h5Vtp/A8nGwnZW+cpBAQDtJ9aEW7UvSUE+1Do5XB2Mgou0gC",
	"XBll8yMJ8MUomxmhTXvo/SNcruPmEq4ferVDu/rOC8QHY5UPvVwIxB4lVRHULjsyCjySRZy5GUlEmroJ",
	"nLWJLCB9b4A5uhvsobO6iR/VeAk5zhkfGZysx+qS7uv1HRxhOHhh7VFOqH/OZkncFUVzPwA3n+FSzY2l",
	"hyCwf7nIhOURamTL7gSDn4uBjz7A3/NmjSgdpixgZq54sHXvjq57jbwguvbzR+evdwrO0fFd/ucR+q0C",
	"7FdmgusLvLGK3lRAxyqildcDXHXO2Bn2PqgLr1YH8dE/pDuslmMzEEDg048I+9Lwm6WeTkTKCbTqlREq",
	"gdafcaq75MCM6rBaoOv4kbUAT+cENuazHAYu1WPdLwOIA/SwhbYPsfUWl+q0A665I+pq7IKak/n44+kQ",
	"/kaI43ane1LtZJFi6IDE7KzFMN6vRbxkUiKqZTwXLpy8zPe9Z+I8sgIO3wV83niGzV1wTN/JSybS5QKz",
	"iDk+9RVkyqdZeu3CNBXgZhUvL/XC36yjPdN5xSOrLvlufHMhb8Asv3AhD/V8ks3ICTXX9R9mnco+axDx",
	"CqWT47SeerCGD+pOmapm4g1fhwqtzfnnuXzvCqSiSGOawF7u78nppqB0iuGnf2peRGD3tr6T96cvhiuO",
	"09cZHAnSnL7Bp/Lxmdysh8v9WfLA3KZjWHmligVWNGZ1s57Pt+hbJqj3RotIbncrO8uAqNTjrS/dedoW",
	"pvfFD1GszBBqBz1sgf6wjdIzycgYD8w+i3iWUdR7l8JaUkMFr7NvEmWxvup0LbI/ALxuoacvhO4t55D3",
	"xp3T6hvse6XPWTY+DKF1RRQM9XR7ehVwo+WIFn1pKl/GbXcYWqO4cxaC5tSoEA6AiACl3hS7UKFc1Qpq",
	"WlHnwFXtPnF1GRL5gDNumI67jUt1ntDir4llQ/Z9igTE2ES+v27Nh/cBQQm3JXGRwrnFjhrSTYY/1PHj",
	"CmAj6yCGHr7F7z+Bzt6nzr4ZNAuaVdQbshHNuQsaCO+fVeWUcE9ysBThJPL90zkJoQmbvwcxbNaj0YT7",
	"SidPE+ck6OmLaDQ5+ZP4xvTZa278480DJ4f7h5hDx5YdV+5zHE4OfanFceq5Hhd6hpDxmyJBSKdtIavm",
	"z+FzLXA6o8i+4wQ3Ebp66HTas9wXzpxxHMdeinQeE8gCqvdx27NVyQe8IaNn9lg0Fcwev+U2cIQH+l6z",
	"x0UcCR6Oqn1TvD4ZCgqULwrlRk4f39Gq2V1eT1hp20f7wbO3fm0mKjoy/vP/y0PS1WFxR2e9plXzzm4L",
	"HRS9Icm+CuI5cvP8VeRZQChSqZv/6mRkuncgdqCmFE3DBhk2jpKjTKp+vqI//Jxq32ueBg6petxZXPxH",
	"AAAA//8=",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
