//go:build go1.22

// Package handler provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package handler

import (
	"errors"
	"fmt"
	"net/http"
	"time"

	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for ArtistGender.
const (
	ArtistGenderFEMALE ArtistGender = "FEMALE"
	ArtistGenderMALE   ArtistGender = "MALE"
	ArtistGenderMIXED  ArtistGender = "MIXED"
	ArtistGenderOTHER  ArtistGender = "OTHER"
)

// Valid indicates whether the value is a known member of the ArtistGender enum.
func (e ArtistGender) Valid() bool {
	switch e {
	case ArtistGenderFEMALE:
		return true
	case ArtistGenderMALE:
		return true
	case ArtistGenderMIXED:
		return true
	case ArtistGenderOTHER:
		return true
	default:
		return false
	}
}

// Defines values for ArtistStatus.
const (
	ArtistStatusAPPROVED ArtistStatus = "APPROVED"
	ArtistStatusPENDING  ArtistStatus = "PENDING"
	ArtistStatusREJECTED ArtistStatus = "REJECTED"
)

// Valid indicates whether the value is a known member of the ArtistStatus enum.
func (e ArtistStatus) Valid() bool {
	switch e {
	case ArtistStatusAPPROVED:
		return true
	case ArtistStatusPENDING:
		return true
	case ArtistStatusREJECTED:
		return true
	default:
		return false
	}
}

// Defines values for ArtistInputGender.
const (
	ArtistInputGenderFEMALE ArtistInputGender = "FEMALE"
	ArtistInputGenderMALE   ArtistInputGender = "MALE"
	ArtistInputGenderMIXED  ArtistInputGender = "MIXED"
	ArtistInputGenderOTHER  ArtistInputGender = "OTHER"
)

// Valid indicates whether the value is a known member of the ArtistInputGender enum.
func (e ArtistInputGender) Valid() bool {
	switch e {
	case ArtistInputGenderFEMALE:
		return true
	case ArtistInputGenderMALE:
		return true
	case ArtistInputGenderMIXED:
		return true
	case ArtistInputGenderOTHER:
		return true
	default:
		return false
	}
}

// Defines values for ArtistSummaryStatus.
const (
	ArtistSummaryStatusAPPROVED ArtistSummaryStatus = "APPROVED"
	ArtistSummaryStatusPENDING  ArtistSummaryStatus = "PENDING"
	ArtistSummaryStatusREJECTED ArtistSummaryStatus = "REJECTED"
)

// Valid indicates whether the value is a known member of the ArtistSummaryStatus enum.
func (e ArtistSummaryStatus) Valid() bool {
	switch e {
	case ArtistSummaryStatusAPPROVED:
		return true
	case ArtistSummaryStatusPENDING:
		return true
	case ArtistSummaryStatusREJECTED:
		return true
	default:
		return false
	}
}

// Defines values for EventStatus.
const (
	EventStatusAPPROVED EventStatus = "APPROVED"
	EventStatusPENDING  EventStatus = "PENDING"
	EventStatusREJECTED EventStatus = "REJECTED"
)

// Valid indicates whether the value is a known member of the EventStatus enum.
func (e EventStatus) Valid() bool {
	switch e {
	case EventStatusAPPROVED:
		return true
	case EventStatusPENDING:
		return true
	case EventStatusREJECTED:
		return true
	default:
		return false
	}
}

// Defines values for EventHistorySummaryStatus.
const (
	ACTIVE   EventHistorySummaryStatus = "ACTIVE"
	REVERTED EventHistorySummaryStatus = "REVERTED"
)

// Valid indicates whether the value is a known member of the EventHistorySummaryStatus enum.
func (e EventHistorySummaryStatus) Valid() bool {
	switch e {
	case ACTIVE:
		return true
	case REVERTED:
		return true
	default:
		return false
	}
}

// Defines values for EventSummaryStatus.
const (
	EventSummaryStatusAPPROVED EventSummaryStatus = "APPROVED"
	EventSummaryStatusPENDING  EventSummaryStatus = "PENDING"
	EventSummaryStatusREJECTED EventSummaryStatus = "REJECTED"
)

// Valid indicates whether the value is a known member of the EventSummaryStatus enum.
func (e EventSummaryStatus) Valid() bool {
	switch e {
	case EventSummaryStatusAPPROVED:
		return true
	case EventSummaryStatusPENDING:
		return true
	case EventSummaryStatusREJECTED:
		return true
	default:
		return false
	}
}

// Defines values for VenueStatus.
const (
	VenueStatusAPPROVED VenueStatus = "APPROVED"
	VenueStatusPENDING  VenueStatus = "PENDING"
	VenueStatusREJECTED VenueStatus = "REJECTED"
)

// Valid indicates whether the value is a known member of the VenueStatus enum.
func (e VenueStatus) Valid() bool {
	switch e {
	case VenueStatusAPPROVED:
		return true
	case VenueStatusPENDING:
		return true
	case VenueStatusREJECTED:
		return true
	default:
		return false
	}
}

// Defines values for VenueSummaryStatus.
const (
	VenueSummaryStatusAPPROVED VenueSummaryStatus = "APPROVED"
	VenueSummaryStatusPENDING  VenueSummaryStatus = "PENDING"
	VenueSummaryStatusREJECTED VenueSummaryStatus = "REJECTED"
)

// Valid indicates whether the value is a known member of the VenueSummaryStatus enum.
func (e VenueSummaryStatus) Valid() bool {
	switch e {
	case VenueSummaryStatusAPPROVED:
		return true
	case VenueSummaryStatusPENDING:
		return true
	case VenueSummaryStatusREJECTED:
		return true
	default:
		return false
	}
}

// Defines values for GetArtistsParamsStatus.
const (
	GetArtistsParamsStatusAPPROVED GetArtistsParamsStatus = "APPROVED"
	GetArtistsParamsStatusPENDING  GetArtistsParamsStatus = "PENDING"
	GetArtistsParamsStatusREJECTED GetArtistsParamsStatus = "REJECTED"
)

// Valid indicates whether the value is a known member of the GetArtistsParamsStatus enum.
func (e GetArtistsParamsStatus) Valid() bool {
	switch e {
	case GetArtistsParamsStatusAPPROVED:
		return true
	case GetArtistsParamsStatusPENDING:
		return true
	case GetArtistsParamsStatusREJECTED:
		return true
	default:
		return false
	}
}

// Defines values for GetEventsParamsTimeRange.
const (
	Past     GetEventsParamsTimeRange = "past"
	Upcoming GetEventsParamsTimeRange = "upcoming"
)

// Valid indicates whether the value is a known member of the GetEventsParamsTimeRange enum.
func (e GetEventsParamsTimeRange) Valid() bool {
	switch e {
	case Past:
		return true
	case Upcoming:
		return true
	default:
		return false
	}
}

// Defines values for GetEventsParamsStatus.
const (
	GetEventsParamsStatusAPPROVED GetEventsParamsStatus = "APPROVED"
	GetEventsParamsStatusPENDING  GetEventsParamsStatus = "PENDING"
	GetEventsParamsStatusREJECTED GetEventsParamsStatus = "REJECTED"
)

// Valid indicates whether the value is a known member of the GetEventsParamsStatus enum.
func (e GetEventsParamsStatus) Valid() bool {
	switch e {
	case GetEventsParamsStatusAPPROVED:
		return true
	case GetEventsParamsStatusPENDING:
		return true
	case GetEventsParamsStatusREJECTED:
		return true
	default:
		return false
	}
}

// Defines values for GetVenuesParamsStatus.
const (
	GetVenuesParamsStatusAPPROVED GetVenuesParamsStatus = "APPROVED"
	GetVenuesParamsStatusPENDING  GetVenuesParamsStatus = "PENDING"
	GetVenuesParamsStatusREJECTED GetVenuesParamsStatus = "REJECTED"
)

// Valid indicates whether the value is a known member of the GetVenuesParamsStatus enum.
func (e GetVenuesParamsStatus) Valid() bool {
	switch e {
	case GetVenuesParamsStatusAPPROVED:
		return true
	case GetVenuesParamsStatusPENDING:
		return true
	case GetVenuesParamsStatusREJECTED:
		return true
	default:
		return false
	}
}

// Artist defines model for Artist.
type Artist struct {
	// AuthorId 등록한 유저 ID
	AuthorId *openapi_types.UUID `json:"authorId,omitempty"`

	// BirthDate 생년월일 (YYYY-MM-DD)
	BirthDate *openapi_types.Date `json:"birthDate,omitempty"`

	// DebutDate 데뷔일 (YYYY-MM-DD)
	DebutDate *openapi_types.Date `json:"debutDate,omitempty"`

	// Gender 성별
	Gender *ArtistGender `json:"gender,omitempty"`

	// Hiragana 히라가나
	Hiragana *string `json:"hiragana,omitempty"`

	// Id 아티스트 고유 식별자
	Id *openapi_types.UUID `json:"id,omitempty"`

	// OfficialName 공식 이름
	OfficialName *string `json:"officialName,omitempty"`

	// ProfileImageUrl 프로필 이미지 URL
	ProfileImageUrl *string `json:"profileImageUrl,omitempty"`

	// Status 아티스트 상태 (유저 등록 시 PENDING, 관리자 승인 시 APPROVED)
	Status *ArtistStatus `json:"status,omitempty"`
}

// ArtistGender 성별
type ArtistGender string

// ArtistStatus 아티스트 상태 (유저 등록 시 PENDING, 관리자 승인 시 APPROVED)
type ArtistStatus string

// ArtistInput defines model for ArtistInput.
type ArtistInput struct {
	// BirthDate 생년월일 (YYYY-MM-DD)
	BirthDate *openapi_types.Date `json:"birthDate,omitempty"`

	// DebutDate 데뷔일 (YYYY-MM-DD)
	DebutDate *openapi_types.Date `json:"debutDate,omitempty"`

	// Gender 성별
	Gender ArtistInputGender `json:"gender"`

	// Hiragana 히라가나
	Hiragana *string `json:"hiragana,omitempty"`

	// OfficialName 공식 이름
	OfficialName string `json:"officialName"`

	// ProfileImage 프로필 이미지 업로드 파일 (최대 5MB, JPG/PNG 형식만 허용)
	ProfileImage *openapi_types.File `json:"profileImage,omitempty"`
}

// ArtistInputGender 성별
type ArtistInputGender string

// ArtistSummary defines model for ArtistSummary.
type ArtistSummary struct {
	// Hiragana 히라가나
	Hiragana *string `json:"hiragana,omitempty"`

	// Id 아티스트 고유 식별자
	Id *openapi_types.UUID `json:"id,omitempty"`

	// OfficialName 공식 이름
	OfficialName *string `json:"officialName,omitempty"`

	// Status 아티스트 상태
	Status *ArtistSummaryStatus `json:"status,omitempty"`
}

// ArtistSummaryStatus 아티스트 상태
type ArtistSummaryStatus string

// Event defines model for Event.
type Event struct {
	Artists        *[]ArtistSummary    `json:"artists,omitempty"`
	EndTime        *time.Time          `json:"endTime,omitempty"`
	Id             *openapi_types.UUID `json:"id,omitempty"`
	OpeningTime    *time.Time          `json:"openingTime,omitempty"`
	PosterImageUrl *string             `json:"posterImageUrl,omitempty"`
	RatingCount    *int                `json:"ratingCount,omitempty"`
	RatingSum      *float64            `json:"ratingSum,omitempty"`
	RelatedLinks   *[]string           `json:"relatedLinks,omitempty"`
	StartTime      *time.Time          `json:"startTime,omitempty"`
	Status         *EventStatus        `json:"status,omitempty"`
	Title          *string             `json:"title,omitempty"`
	Venue          *VenueSummary       `json:"venue,omitempty"`
}

// EventStatus defines model for Event.Status.
type EventStatus string

// EventHistorySummary defines model for EventHistorySummary.
type EventHistorySummary struct {
	CreatedAt   *time.Time                 `json:"createdAt,omitempty"`
	EditorId    *openapi_types.UUID        `json:"editorId,omitempty"`
	EventId     *openapi_types.UUID        `json:"eventId,omitempty"`
	Id          *openapi_types.UUID        `json:"id,omitempty"`
	ReportCount *int                       `json:"reportCount,omitempty"`
	Status      *EventHistorySummaryStatus `json:"status,omitempty"`
}

// EventHistorySummaryStatus defines model for EventHistorySummary.Status.
type EventHistorySummaryStatus string

// EventInput defines model for EventInput.
type EventInput struct {
	ArtistIds    *[]openapi_types.UUID `json:"artistIds,omitempty"`
	EndTime      time.Time             `json:"endTime"`
	OpeningTime  *time.Time            `json:"openingTime,omitempty"`
	PosterImage  *openapi_types.File   `json:"posterImage,omitempty"`
	RelatedLinks *[]string             `json:"relatedLinks,omitempty"`
	StartTime    time.Time             `json:"startTime"`
	Title        string                `json:"title"`
	VenueId      openapi_types.UUID    `json:"venueId"`
}

// EventListResponse defines model for EventListResponse.
type EventListResponse struct {
	Events  *[]EventSummary `json:"events,omitempty"`
	HasMore *bool           `json:"hasMore,omitempty"`
}

// EventSummary defines model for EventSummary.
type EventSummary struct {
	EndTime        *time.Time          `json:"endTime,omitempty"`
	Id             *openapi_types.UUID `json:"id,omitempty"`
	PosterImageUrl *string             `json:"posterImageUrl,omitempty"`
	Rating         *float64            `json:"rating,omitempty"`
	StartTime      *time.Time          `json:"startTime,omitempty"`
	Status         *EventSummaryStatus `json:"status,omitempty"`
	Title          *string             `json:"title,omitempty"`
	VenueId        *openapi_types.UUID `json:"venueId,omitempty"`
}

// EventSummaryStatus defines model for EventSummary.Status.
type EventSummaryStatus string

// EventThread defines model for EventThread.
type EventThread struct {
	AuthorId       *openapi_types.UUID `json:"authorId,omitempty"`
	Content        *string             `json:"content,omitempty"`
	CreatedAt      *time.Time          `json:"createdAt,omitempty"`
	EventId        *openapi_types.UUID `json:"eventId,omitempty"`
	Id             *openapi_types.UUID `json:"id,omitempty"`
	RecommendCount *int                `json:"recommendCount,omitempty"`
}

// EventThreadInput defines model for EventThreadInput.
type EventThreadInput struct {
	Content string `json:"content"`
}

// GoogleLoginRequest defines model for GoogleLoginRequest.
type GoogleLoginRequest struct {
	// IdToken 클라이언트로부터 전달받은 구글 ID 토큰
	IdToken string `json:"idToken"`
}

// LinkGoogleRequest defines model for LinkGoogleRequest.
type LinkGoogleRequest struct {
	// IdToken 클라이언트로부터 전달받은 구글 ID 토큰
	IdToken string `json:"idToken"`
}

// LocalLoginRequest defines model for LocalLoginRequest.
type LocalLoginRequest struct {
	// Email 사용자의 이메일 주소
	Email openapi_types.Email `json:"email"`

	// Password 사용자의 비밀번호
	Password string `json:"password"`
}

// RatingInput defines model for RatingInput.
type RatingInput struct {
	Score int `json:"score"`
}

// SignupRequest defines model for SignupRequest.
type SignupRequest struct {
	// Email 사용자의 이메일 주소
	Email openapi_types.Email `json:"email"`

	// Nickname 사용자가 선택한 표시 이름(닉네임)
	Nickname string `json:"nickname"`

	// Password 사용자의 비밀번호
	Password string `json:"password"`
}

// TokenResponse defines model for TokenResponse.
type TokenResponse struct {
	// AccessToken 애플리케이션 액세스 토큰 (JWT)
	AccessToken string `json:"accessToken"`
}

// Venue defines model for Venue.
type Venue struct {
	Address  *string `json:"address,omitempty"`
	Capacity *int    `json:"capacity,omitempty"`

	// GoogleMapId Google Maps Place ID
	GoogleMapId  *string             `json:"googleMapId,omitempty"`
	Id           *openapi_types.UUID `json:"id,omitempty"`
	Latitude     *float64            `json:"latitude,omitempty"`
	Longitude    *float64            `json:"longitude,omitempty"`
	OfficialName *string             `json:"officialName,omitempty"`
	Rating       *float64            `json:"rating,omitempty"`
	RatingCount  *int                `json:"ratingCount,omitempty"`
	RelatedLinks *[]string           `json:"relatedLinks,omitempty"`
	Status       *VenueStatus        `json:"status,omitempty"`
}

// VenueStatus defines model for Venue.Status.
type VenueStatus string

// VenueInput defines model for VenueInput.
type VenueInput struct {
	Address      *string   `json:"address,omitempty"`
	Capacity     *int      `json:"capacity,omitempty"`
	GoogleMapId  *string   `json:"googleMapId,omitempty"`
	Latitude     float64   `json:"latitude"`
	Longitude    float64   `json:"longitude"`
	OfficialName string    `json:"officialName"`
	RelatedLinks *[]string `json:"relatedLinks,omitempty"`
}

// VenueListResponse defines model for VenueListResponse.
type VenueListResponse struct {
	// HasMore 결과가 최대치(100개)를 초과하여 더 존재하는지 여부
	HasMore *bool           `json:"hasMore,omitempty"`
	Venues  *[]VenueSummary `json:"venues,omitempty"`
}

// VenueSummary defines model for VenueSummary.
type VenueSummary struct {
	// Id 공연장 고유 식별자
	Id *openapi_types.UUID `json:"id,omitempty"`

	// Latitude 위도
	Latitude *float64 `json:"latitude,omitempty"`

	// Longitude 경도
	Longitude *float64 `json:"longitude,omitempty"`

	// OfficialName 공식 이름
	OfficialName *string `json:"officialName,omitempty"`

	// Rating 런닝 토탈 방식의 평균 평점
	Rating *float64 `json:"rating,omitempty"`

	// Status 공연장 승인 상태
	Status *VenueSummaryStatus `json:"status,omitempty"`
}

// VenueSummaryStatus 공연장 승인 상태
type VenueSummaryStatus string

// GetArtistsParams defines parameters for GetArtists.
type GetArtistsParams struct {
	// Query 검색어 (초성, 영문, 히라가나 등)
	Query *string `form:"query,omitempty" json:"query,omitempty"`

	// Status 특정 상태의 아티스트만 필터링 (선택)
	Status *GetArtistsParamsStatus `form:"status,omitempty" json:"status,omitempty"`
}

// GetArtistsParamsStatus defines parameters for GetArtists.
type GetArtistsParamsStatus string

// PostAuthLogoutParams defines parameters for PostAuthLogout.
type PostAuthLogoutParams struct {
	// RefreshToken 무효화할 리프레시 토큰
	RefreshToken string `form:"refreshToken" json:"refreshToken"`
}

// PostAuthRefreshParams defines parameters for PostAuthRefresh.
type PostAuthRefreshParams struct {
	// RefreshToken HttpOnly 리프레시 토큰
	RefreshToken string `form:"refreshToken" json:"refreshToken"`
}

// GetEventsParams defines parameters for GetEvents.
type GetEventsParams struct {
	ArtistId  *openapi_types.UUID       `form:"artistId,omitempty" json:"artistId,omitempty"`
	VenueId   *openapi_types.UUID       `form:"venueId,omitempty" json:"venueId,omitempty"`
	TimeRange *GetEventsParamsTimeRange `form:"timeRange,omitempty" json:"timeRange,omitempty"`
	Status    *GetEventsParamsStatus    `form:"status,omitempty" json:"status,omitempty"`
}

// GetEventsParamsTimeRange defines parameters for GetEvents.
type GetEventsParamsTimeRange string

// GetEventsParamsStatus defines parameters for GetEvents.
type GetEventsParamsStatus string

// GetVenuesParams defines parameters for GetVenues.
type GetVenuesParams struct {
	// MinLat 최소 위도 (남쪽 경계)
	MinLat float64 `form:"minLat" json:"minLat"`

	// MaxLat 최대 위도 (북쪽 경계)
	MaxLat float64 `form:"maxLat" json:"maxLat"`

	// MinLng 최소 경도 (서쪽 경계)
	MinLng float64 `form:"minLng" json:"minLng"`

	// MaxLng 최대 경도 (동쪽 경계)
	MaxLng float64 `form:"maxLng" json:"maxLng"`

	// Query 공연장 이름 검색어 (선택)
	Query *string `form:"query,omitempty" json:"query,omitempty"`

	// Status 상태 필터링 (선택)
	Status *GetVenuesParamsStatus `form:"status,omitempty" json:"status,omitempty"`
}

// GetVenuesParamsStatus defines parameters for GetVenues.
type GetVenuesParamsStatus string

// PostArtistsMultipartRequestBody defines body for PostArtists for multipart/form-data ContentType.
type PostArtistsMultipartRequestBody = ArtistInput

// PutArtistsArtistIdMultipartRequestBody defines body for PutArtistsArtistId for multipart/form-data ContentType.
type PutArtistsArtistIdMultipartRequestBody = ArtistInput

// PostAuthGoogleJSONRequestBody defines body for PostAuthGoogle for application/json ContentType.
type PostAuthGoogleJSONRequestBody = GoogleLoginRequest

// PostAuthLoginJSONRequestBody defines body for PostAuthLogin for application/json ContentType.
type PostAuthLoginJSONRequestBody = LocalLoginRequest

// PostAuthSignupJSONRequestBody defines body for PostAuthSignup for application/json ContentType.
type PostAuthSignupJSONRequestBody = SignupRequest

// PostEventsMultipartRequestBody defines body for PostEvents for multipart/form-data ContentType.
type PostEventsMultipartRequestBody = EventInput

// PutEventsEventIdMultipartRequestBody defines body for PutEventsEventId for multipart/form-data ContentType.
type PutEventsEventIdMultipartRequestBody = EventInput

// PostEventsEventIdRateJSONRequestBody defines body for PostEventsEventIdRate for application/json ContentType.
type PostEventsEventIdRateJSONRequestBody = RatingInput

// PostEventsEventIdThreadsJSONRequestBody defines body for PostEventsEventIdThreads for application/json ContentType.
type PostEventsEventIdThreadsJSONRequestBody = EventThreadInput

// PostUsersMeLinkGoogleJSONRequestBody defines body for PostUsersMeLinkGoogle for application/json ContentType.
type PostUsersMeLinkGoogleJSONRequestBody = LinkGoogleRequest

// PostVenuesJSONRequestBody defines body for PostVenues for application/json ContentType.
type PostVenuesJSONRequestBody = VenueInput

// PutVenuesVenueIdJSONRequestBody defines body for PutVenuesVenueId for application/json ContentType.
type PutVenuesVenueIdJSONRequestBody = VenueInput

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// GetArtists 아티스트 목록 조회 (통합)
	// (GET /artists)
	GetArtists(w http.ResponseWriter, r *http.Request, params GetArtistsParams)
	// PostArtists 아티스트 등록
	// (POST /artists)
	PostArtists(w http.ResponseWriter, r *http.Request)
	// DeleteArtistsArtistId 아티스트 삭제
	// (DELETE /artists/{artistId})
	DeleteArtistsArtistId(w http.ResponseWriter, r *http.Request, artistId openapi_types.UUID)
	// GetArtistsArtistId 아티스트 상세 정보 조회
	// (GET /artists/{artistId})
	GetArtistsArtistId(w http.ResponseWriter, r *http.Request, artistId openapi_types.UUID)
	// PutArtistsArtistId 아티스트 수정
	// (PUT /artists/{artistId})
	PutArtistsArtistId(w http.ResponseWriter, r *http.Request, artistId openapi_types.UUID)
	// PostArtistsArtistIdApprove 아티스트 승인 (관리자 전용)
	// (POST /artists/{artistId}/approve)
	PostArtistsArtistIdApprove(w http.ResponseWriter, r *http.Request, artistId openapi_types.UUID)
	// PostAuthGoogle 구글 로그인
	// (POST /auth/google)
	PostAuthGoogle(w http.ResponseWriter, r *http.Request)
	// PostAuthLogin 로컬 로그인
	// (POST /auth/login)
	PostAuthLogin(w http.ResponseWriter, r *http.Request)
	// PostAuthLogout 로그아웃
	// (POST /auth/logout)
	PostAuthLogout(w http.ResponseWriter, r *http.Request, params PostAuthLogoutParams)
	// PostAuthRefresh 액세스 토큰 갱신
	// (POST /auth/refresh)
	PostAuthRefresh(w http.ResponseWriter, r *http.Request, params PostAuthRefreshParams)
	// PostAuthSignup 로컬 회원가입
	// (POST /auth/signup)
	PostAuthSignup(w http.ResponseWriter, r *http.Request)
	// PostEventHistoryHistoryIdReport 수정 이력 신고
	// (POST /event-history/{historyId}/report)
	PostEventHistoryHistoryIdReport(w http.ResponseWriter, r *http.Request, historyId openapi_types.UUID)
	// PostEventThreadsThreadIdRecommend 스레드 추천 토글
	// (POST /event-threads/{threadId}/recommend)
	PostEventThreadsThreadIdRecommend(w http.ResponseWriter, r *http.Request, threadId openapi_types.UUID)
	// GetEvents 이벤트 목록 조회
	// (GET /events)
	GetEvents(w http.ResponseWriter, r *http.Request, params GetEventsParams)
	// PostEvents 이벤트 등록 (위키 방식)
	// (POST /events)
	PostEvents(w http.ResponseWriter, r *http.Request)
	// GetEventsEventId 이벤트 상세 조회
	// (GET /events/{eventId})
	GetEventsEventId(w http.ResponseWriter, r *http.Request, eventId openapi_types.UUID)
	// PutEventsEventId 이벤트 수정 (위키 방식)
	// (PUT /events/{eventId})
	PutEventsEventId(w http.ResponseWriter, r *http.Request, eventId openapi_types.UUID)
	// PostEventsEventIdAttend 참가/취소 토글
	// (POST /events/{eventId}/attend)
	PostEventsEventIdAttend(w http.ResponseWriter, r *http.Request, eventId openapi_types.UUID)
	// PostEventsEventIdDeleteRequest 이벤트 삭제 요청
	// (POST /events/{eventId}/delete-request)
	PostEventsEventIdDeleteRequest(w http.ResponseWriter, r *http.Request, eventId openapi_types.UUID)
	// GetEventsEventIdHistory 이벤트 수정 이력 조회
	// (GET /events/{eventId}/history)
	GetEventsEventIdHistory(w http.ResponseWriter, r *http.Request, eventId openapi_types.UUID)
	// PostEventsEventIdRate 이벤트 평점 등록
	// (POST /events/{eventId}/rate)
	PostEventsEventIdRate(w http.ResponseWriter, r *http.Request, eventId openapi_types.UUID)
	// GetEventsEventIdThreads 이벤트 스레드(부가정보) 조회
	// (GET /events/{eventId}/threads)
	GetEventsEventIdThreads(w http.ResponseWriter, r *http.Request, eventId openapi_types.UUID)
	// PostEventsEventIdThreads 이벤트 스레드 작성
	// (POST /events/{eventId}/threads)
	PostEventsEventIdThreads(w http.ResponseWriter, r *http.Request, eventId openapi_types.UUID)
	// GetPing 서버 상태 확인
	// (GET /ping)
	GetPing(w http.ResponseWriter, r *http.Request)
	// PostUsersMeLinkGoogle 구글 계정 연동
	// (POST /users/me/link-google)
	PostUsersMeLinkGoogle(w http.ResponseWriter, r *http.Request)
	// GetVenues 공연장 목록 조회 (지도 기반)
	// (GET /venues)
	GetVenues(w http.ResponseWriter, r *http.Request, params GetVenuesParams)
	// PostVenues 공연장 등록
	// (POST /venues)
	PostVenues(w http.ResponseWriter, r *http.Request)
	// DeleteVenuesVenueId 공연장 삭제
	// (DELETE /venues/{venueId})
	DeleteVenuesVenueId(w http.ResponseWriter, r *http.Request, venueId openapi_types.UUID)
	// GetVenuesVenueId 공연장 상세 정보 조회
	// (GET /venues/{venueId})
	GetVenuesVenueId(w http.ResponseWriter, r *http.Request, venueId openapi_types.UUID)
	// PutVenuesVenueId 공연장 수정
	// (PUT /venues/{venueId})
	PutVenuesVenueId(w http.ResponseWriter, r *http.Request, venueId openapi_types.UUID)
	// PostVenuesVenueIdApprove 공연장 승인 (관리자 전용)
	// (POST /venues/{venueId}/approve)
	PostVenuesVenueIdApprove(w http.ResponseWriter, r *http.Request, venueId openapi_types.UUID)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetArtists operation middleware
func (siw *ServerInterfaceWrapper) GetArtists(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params GetArtistsParams

	// ------------- Optional query parameter "query" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "query", r.URL.Query(), &params.Query, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "query"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "query", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "status", r.URL.Query(), &params.Status, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "status"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "status", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetArtists(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostArtists operation middleware
func (siw *ServerInterfaceWrapper) PostArtists(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostArtists(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteArtistsArtistId operation middleware
func (siw *ServerInterfaceWrapper) DeleteArtistsArtistId(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "artistId" -------------
	var artistId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "artistId", r.PathValue("artistId"), &artistId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "artistId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteArtistsArtistId(w, r, artistId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetArtistsArtistId operation middleware
func (siw *ServerInterfaceWrapper) GetArtistsArtistId(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "artistId" -------------
	var artistId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "artistId", r.PathValue("artistId"), &artistId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "artistId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetArtistsArtistId(w, r, artistId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PutArtistsArtistId operation middleware
func (siw *ServerInterfaceWrapper) PutArtistsArtistId(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "artistId" -------------
	var artistId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "artistId", r.PathValue("artistId"), &artistId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "artistId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PutArtistsArtistId(w, r, artistId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostArtistsArtistIdApprove operation middleware
func (siw *ServerInterfaceWrapper) PostArtistsArtistIdApprove(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "artistId" -------------
	var artistId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "artistId", r.PathValue("artistId"), &artistId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "artistId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostArtistsArtistIdApprove(w, r, artistId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostAuthGoogle operation middleware
func (siw *ServerInterfaceWrapper) PostAuthGoogle(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostAuthGoogle(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostAuthLogin operation middleware
func (siw *ServerInterfaceWrapper) PostAuthLogin(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostAuthLogin(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostAuthLogout operation middleware
func (siw *ServerInterfaceWrapper) PostAuthLogout(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params PostAuthLogoutParams

	{
		var cookie *http.Cookie

		if cookie, err = r.Cookie("refreshToken"); err == nil {
			var value string
			err = runtime.BindStyledParameterWithOptions("simple", "refreshToken", cookie.Value, &value, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationCookie, Explode: true, Required: true, Type: "string", Format: ""})
			if err != nil {
				siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "refreshToken", Err: err})
				return
			}
			params.RefreshToken = value

		} else {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "refreshToken"})
			return
		}
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostAuthLogout(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostAuthRefresh operation middleware
func (siw *ServerInterfaceWrapper) PostAuthRefresh(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params PostAuthRefreshParams

	{
		var cookie *http.Cookie

		if cookie, err = r.Cookie("refreshToken"); err == nil {
			var value string
			err = runtime.BindStyledParameterWithOptions("simple", "refreshToken", cookie.Value, &value, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationCookie, Explode: true, Required: true, Type: "string", Format: ""})
			if err != nil {
				siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "refreshToken", Err: err})
				return
			}
			params.RefreshToken = value

		} else {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "refreshToken"})
			return
		}
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostAuthRefresh(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostAuthSignup operation middleware
func (siw *ServerInterfaceWrapper) PostAuthSignup(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostAuthSignup(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostEventHistoryHistoryIdReport operation middleware
func (siw *ServerInterfaceWrapper) PostEventHistoryHistoryIdReport(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "historyId" -------------
	var historyId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "historyId", r.PathValue("historyId"), &historyId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "historyId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostEventHistoryHistoryIdReport(w, r, historyId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostEventThreadsThreadIdRecommend operation middleware
func (siw *ServerInterfaceWrapper) PostEventThreadsThreadIdRecommend(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "threadId" -------------
	var threadId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "threadId", r.PathValue("threadId"), &threadId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "threadId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostEventThreadsThreadIdRecommend(w, r, threadId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetEvents operation middleware
func (siw *ServerInterfaceWrapper) GetEvents(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params GetEventsParams

	// ------------- Optional query parameter "artistId" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "artistId", r.URL.Query(), &params.ArtistId, runtime.BindQueryParameterOptions{Type: "string", Format: "uuid"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "artistId"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "artistId", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "venueId" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "venueId", r.URL.Query(), &params.VenueId, runtime.BindQueryParameterOptions{Type: "string", Format: "uuid"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "venueId"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "venueId", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "timeRange" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "timeRange", r.URL.Query(), &params.TimeRange, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "timeRange"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "timeRange", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "status", r.URL.Query(), &params.Status, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "status"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "status", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetEvents(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostEvents operation middleware
func (siw *ServerInterfaceWrapper) PostEvents(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostEvents(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetEventsEventId operation middleware
func (siw *ServerInterfaceWrapper) GetEventsEventId(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "eventId" -------------
	var eventId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "eventId", r.PathValue("eventId"), &eventId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "eventId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetEventsEventId(w, r, eventId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PutEventsEventId operation middleware
func (siw *ServerInterfaceWrapper) PutEventsEventId(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "eventId" -------------
	var eventId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "eventId", r.PathValue("eventId"), &eventId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "eventId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PutEventsEventId(w, r, eventId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostEventsEventIdAttend operation middleware
func (siw *ServerInterfaceWrapper) PostEventsEventIdAttend(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "eventId" -------------
	var eventId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "eventId", r.PathValue("eventId"), &eventId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "eventId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostEventsEventIdAttend(w, r, eventId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostEventsEventIdDeleteRequest operation middleware
func (siw *ServerInterfaceWrapper) PostEventsEventIdDeleteRequest(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "eventId" -------------
	var eventId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "eventId", r.PathValue("eventId"), &eventId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "eventId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostEventsEventIdDeleteRequest(w, r, eventId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetEventsEventIdHistory operation middleware
func (siw *ServerInterfaceWrapper) GetEventsEventIdHistory(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "eventId" -------------
	var eventId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "eventId", r.PathValue("eventId"), &eventId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "eventId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetEventsEventIdHistory(w, r, eventId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostEventsEventIdRate operation middleware
func (siw *ServerInterfaceWrapper) PostEventsEventIdRate(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "eventId" -------------
	var eventId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "eventId", r.PathValue("eventId"), &eventId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "eventId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostEventsEventIdRate(w, r, eventId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetEventsEventIdThreads operation middleware
func (siw *ServerInterfaceWrapper) GetEventsEventIdThreads(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "eventId" -------------
	var eventId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "eventId", r.PathValue("eventId"), &eventId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "eventId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetEventsEventIdThreads(w, r, eventId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostEventsEventIdThreads operation middleware
func (siw *ServerInterfaceWrapper) PostEventsEventIdThreads(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "eventId" -------------
	var eventId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "eventId", r.PathValue("eventId"), &eventId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "eventId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostEventsEventIdThreads(w, r, eventId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetPing operation middleware
func (siw *ServerInterfaceWrapper) GetPing(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetPing(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostUsersMeLinkGoogle operation middleware
func (siw *ServerInterfaceWrapper) PostUsersMeLinkGoogle(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostUsersMeLinkGoogle(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetVenues operation middleware
func (siw *ServerInterfaceWrapper) GetVenues(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params GetVenuesParams

	// ------------- Required query parameter "minLat" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "minLat", r.URL.Query(), &params.MinLat, runtime.BindQueryParameterOptions{Type: "number", Format: "double"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "minLat"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "minLat", Err: err})
		}
		return
	}

	// ------------- Required query parameter "maxLat" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "maxLat", r.URL.Query(), &params.MaxLat, runtime.BindQueryParameterOptions{Type: "number", Format: "double"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "maxLat"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "maxLat", Err: err})
		}
		return
	}

	// ------------- Required query parameter "minLng" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "minLng", r.URL.Query(), &params.MinLng, runtime.BindQueryParameterOptions{Type: "number", Format: "double"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "minLng"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "minLng", Err: err})
		}
		return
	}

	// ------------- Required query parameter "maxLng" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "maxLng", r.URL.Query(), &params.MaxLng, runtime.BindQueryParameterOptions{Type: "number", Format: "double"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "maxLng"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "maxLng", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "query" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "query", r.URL.Query(), &params.Query, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "query"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "query", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "status", r.URL.Query(), &params.Status, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "status"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "status", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetVenues(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostVenues operation middleware
func (siw *ServerInterfaceWrapper) PostVenues(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostVenues(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteVenuesVenueId operation middleware
func (siw *ServerInterfaceWrapper) DeleteVenuesVenueId(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "venueId" -------------
	var venueId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "venueId", r.PathValue("venueId"), &venueId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "venueId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteVenuesVenueId(w, r, venueId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetVenuesVenueId operation middleware
func (siw *ServerInterfaceWrapper) GetVenuesVenueId(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "venueId" -------------
	var venueId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "venueId", r.PathValue("venueId"), &venueId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "venueId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetVenuesVenueId(w, r, venueId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PutVenuesVenueId operation middleware
func (siw *ServerInterfaceWrapper) PutVenuesVenueId(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "venueId" -------------
	var venueId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "venueId", r.PathValue("venueId"), &venueId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "venueId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PutVenuesVenueId(w, r, venueId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostVenuesVenueIdApprove operation middleware
func (siw *ServerInterfaceWrapper) PostVenuesVenueIdApprove(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "venueId" -------------
	var venueId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "venueId", r.PathValue("venueId"), &venueId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "venueId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostVenuesVenueIdApprove(w, r, venueId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/ping", wrapper.GetPing)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/auth/google", wrapper.PostAuthGoogle)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/auth/refresh", wrapper.PostAuthRefresh)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/auth/signup", wrapper.PostAuthSignup)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/auth/login", wrapper.PostAuthLogin)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/users/me/link-google", wrapper.PostUsersMeLinkGoogle)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/auth/logout", wrapper.PostAuthLogout)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/artists", wrapper.GetArtists)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/artists", wrapper.PostArtists)
	m.HandleFunc(http.MethodDelete+" "+options.BaseURL+"/artists/{artistId}", wrapper.DeleteArtistsArtistId)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/artists/{artistId}", wrapper.GetArtistsArtistId)
	m.HandleFunc(http.MethodPut+" "+options.BaseURL+"/artists/{artistId}", wrapper.PutArtistsArtistId)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/artists/{artistId}/approve", wrapper.PostArtistsArtistIdApprove)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/venues", wrapper.GetVenues)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/venues", wrapper.PostVenues)
	m.HandleFunc(http.MethodDelete+" "+options.BaseURL+"/venues/{venueId}", wrapper.DeleteVenuesVenueId)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/venues/{venueId}", wrapper.GetVenuesVenueId)
	m.HandleFunc(http.MethodPut+" "+options.BaseURL+"/venues/{venueId}", wrapper.PutVenuesVenueId)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/venues/{venueId}/approve", wrapper.PostVenuesVenueIdApprove)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/events", wrapper.GetEvents)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/events", wrapper.PostEvents)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/events/{eventId}", wrapper.GetEventsEventId)
	m.HandleFunc(http.MethodPut+" "+options.BaseURL+"/events/{eventId}", wrapper.PutEventsEventId)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/events/{eventId}/delete-request", wrapper.PostEventsEventIdDeleteRequest)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/events/{eventId}/attend", wrapper.PostEventsEventIdAttend)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/events/{eventId}/rate", wrapper.PostEventsEventIdRate)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/events/{eventId}/threads", wrapper.GetEventsEventIdThreads)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/events/{eventId}/threads", wrapper.PostEventsEventIdThreads)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/event-threads/{threadId}/recommend", wrapper.PostEventThreadsThreadIdRecommend)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/events/{eventId}/history", wrapper.GetEventsEventIdHistory)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/event-history/{historyId}/report", wrapper.PostEventHistoryHistoryIdReport)

	return m
}
