// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: artist.sql

package repository

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createArtist = `-- name: CreateArtist :one
INSERT INTO artists (official_name, hiragana, gender, profile_image_url, birth_date, debut_date, status, author_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, official_name, hiragana, gender, profile_image_url, birth_date, debut_date, rating_sum, rating_count, status, author_id, created_at, updated_at
`

type CreateArtistParams struct {
	OfficialName    string
	Hiragana        sql.NullString
	Gender          string
	ProfileImageUrl sql.NullString
	BirthDate       sql.NullTime
	DebutDate       sql.NullTime
	Status          string
	AuthorID        uuid.NullUUID
}

func (q *Queries) CreateArtist(ctx context.Context, arg CreateArtistParams) (Artist, error) {
	row := q.db.QueryRowContext(ctx, createArtist,
		arg.OfficialName,
		arg.Hiragana,
		arg.Gender,
		arg.ProfileImageUrl,
		arg.BirthDate,
		arg.DebutDate,
		arg.Status,
		arg.AuthorID,
	)
	var i Artist
	err := row.Scan(
		&i.ID,
		&i.OfficialName,
		&i.Hiragana,
		&i.Gender,
		&i.ProfileImageUrl,
		&i.BirthDate,
		&i.DebutDate,
		&i.RatingSum,
		&i.RatingCount,
		&i.Status,
		&i.AuthorID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getArtist = `-- name: GetArtist :one
SELECT id, official_name, hiragana, gender, profile_image_url, birth_date, debut_date, rating_sum, rating_count, status, author_id, created_at, updated_at FROM artists
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetArtist(ctx context.Context, id uuid.UUID) (Artist, error) {
	row := q.db.QueryRowContext(ctx, getArtist, id)
	var i Artist
	err := row.Scan(
		&i.ID,
		&i.OfficialName,
		&i.Hiragana,
		&i.Gender,
		&i.ProfileImageUrl,
		&i.BirthDate,
		&i.DebutDate,
		&i.RatingSum,
		&i.RatingCount,
		&i.Status,
		&i.AuthorID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listArtists = `-- name: ListArtists :many
SELECT id, official_name, hiragana, gender, profile_image_url, birth_date, debut_date, rating_sum, rating_count, status, author_id, created_at, updated_at FROM artists
WHERE 
    ($2::varchar IS NULL OR status = $2)
    AND ($3::varchar IS NULL OR official_name LIKE $3 || '%')
    AND ($4::uuid IS NULL OR id > $4)
ORDER BY id ASC
LIMIT $1
`

type ListArtistsParams struct {
	Limit       int32
	Status      string
	NameKeyword string
	CursorID    uuid.UUID
}

func (q *Queries) ListArtists(ctx context.Context, arg ListArtistsParams) ([]Artist, error) {
	rows, err := q.db.QueryContext(ctx, listArtists,
		arg.Limit,
		arg.Status,
		arg.NameKeyword,
		arg.CursorID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Artist
	for rows.Next() {
		var i Artist
		if err := rows.Scan(
			&i.ID,
			&i.OfficialName,
			&i.Hiragana,
			&i.Gender,
			&i.ProfileImageUrl,
			&i.BirthDate,
			&i.DebutDate,
			&i.RatingSum,
			&i.RatingCount,
			&i.Status,
			&i.AuthorID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateArtist = `-- name: UpdateArtist :one
UPDATE artists
SET official_name = COALESCE($1, official_name),
    hiragana = COALESCE($2, hiragana),
    gender = COALESCE($3, gender),
    profile_image_url = COALESCE($4, profile_image_url),
    birth_date = COALESCE($5, birth_date),
    debut_date = COALESCE($6, debut_date),
    status = COALESCE($7, status),
    updated_at = NOW()
WHERE id = $8
RETURNING id, official_name, hiragana, gender, profile_image_url, birth_date, debut_date, rating_sum, rating_count, status, author_id, created_at, updated_at
`

type UpdateArtistParams struct {
	OfficialName    sql.NullString
	Hiragana        sql.NullString
	Gender          sql.NullString
	ProfileImageUrl sql.NullString
	BirthDate       sql.NullTime
	DebutDate       sql.NullTime
	Status          sql.NullString
	ID              uuid.UUID
}

func (q *Queries) UpdateArtist(ctx context.Context, arg UpdateArtistParams) (Artist, error) {
	row := q.db.QueryRowContext(ctx, updateArtist,
		arg.OfficialName,
		arg.Hiragana,
		arg.Gender,
		arg.ProfileImageUrl,
		arg.BirthDate,
		arg.DebutDate,
		arg.Status,
		arg.ID,
	)
	var i Artist
	err := row.Scan(
		&i.ID,
		&i.OfficialName,
		&i.Hiragana,
		&i.Gender,
		&i.ProfileImageUrl,
		&i.BirthDate,
		&i.DebutDate,
		&i.RatingSum,
		&i.RatingCount,
		&i.Status,
		&i.AuthorID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateArtistRating = `-- name: UpdateArtistRating :exec
UPDATE artists
SET rating_sum = rating_sum + $1,
    rating_count = rating_count + $2
WHERE id = $3
`

type UpdateArtistRatingParams struct {
	ScoreDelta float64
	CountDelta int32
	ID         uuid.UUID
}

func (q *Queries) UpdateArtistRating(ctx context.Context, arg UpdateArtistRatingParams) error {
	_, err := q.db.ExecContext(ctx, updateArtistRating, arg.ScoreDelta, arg.CountDelta, arg.ID)
	return err
}
