// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: artist_social.sql

package repository

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const followArtist = `-- name: FollowArtist :exec
INSERT INTO user_artist_follows (user_id, artist_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type FollowArtistParams struct {
	UserID   uuid.UUID
	ArtistID uuid.UUID
}

func (q *Queries) FollowArtist(ctx context.Context, arg FollowArtistParams) error {
	_, err := q.db.ExecContext(ctx, followArtist, arg.UserID, arg.ArtistID)
	return err
}

const getLastArtistFeedCheckedAt = `-- name: GetLastArtistFeedCheckedAt :one
SELECT last_artist_feed_checked_at FROM users WHERE id = $1
`

func (q *Queries) GetLastArtistFeedCheckedAt(ctx context.Context, id uuid.UUID) (time.Time, error) {
	row := q.db.QueryRowContext(ctx, getLastArtistFeedCheckedAt, id)
	var last_artist_feed_checked_at time.Time
	err := row.Scan(&last_artist_feed_checked_at)
	return last_artist_feed_checked_at, err
}

const listArtistFollowers = `-- name: ListArtistFollowers :many
SELECT u.id, u.email, u.display_name, u.created_at
FROM users u
JOIN user_artist_follows uaf ON u.id = uaf.user_id
WHERE uaf.artist_id = $1
ORDER BY uaf.created_at DESC
LIMIT $2 OFFSET $3
`

type ListArtistFollowersParams struct {
	ArtistID uuid.UUID
	Limit    int32
	Offset   int32
}

type ListArtistFollowersRow struct {
	ID          uuid.UUID
	Email       sql.NullString
	DisplayName string
	CreatedAt   time.Time
}

func (q *Queries) ListArtistFollowers(ctx context.Context, arg ListArtistFollowersParams) ([]ListArtistFollowersRow, error) {
	rows, err := q.db.QueryContext(ctx, listArtistFollowers, arg.ArtistID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListArtistFollowersRow
	for rows.Next() {
		var i ListArtistFollowersRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.DisplayName,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFollowingArtistEvents = `-- name: ListFollowingArtistEvents :many
SELECT DISTINCT e.id, e.title, e.venue_id, e.opening_time, e.start_time, e.end_time, e.related_links, e.poster_image_url, e.rating_sum, e.rating_count, e.status, e.author_id, e.created_at, e.updated_at
FROM events e
JOIN event_artists ea ON e.id = ea.event_id
JOIN user_artist_follows uaf ON ea.artist_id = uaf.artist_id
WHERE uaf.user_id = $1
ORDER BY e.start_time DESC
LIMIT $2 OFFSET $3
`

type ListFollowingArtistEventsParams struct {
	UserID uuid.UUID
	Limit  int32
	Offset int32
}

func (q *Queries) ListFollowingArtistEvents(ctx context.Context, arg ListFollowingArtistEventsParams) ([]Event, error) {
	rows, err := q.db.QueryContext(ctx, listFollowingArtistEvents, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.VenueID,
			&i.OpeningTime,
			&i.StartTime,
			&i.EndTime,
			pq.Array(&i.RelatedLinks),
			&i.PosterImageUrl,
			&i.RatingSum,
			&i.RatingCount,
			&i.Status,
			&i.AuthorID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFollowingArtists = `-- name: ListFollowingArtists :many
SELECT a.id, a.official_name, a.hiragana, a.gender, a.profile_image_url, a.birth_date, a.debut_date, a.rating_sum, a.rating_count, a.status, a.author_id, a.created_at, a.updated_at
FROM artists a
JOIN user_artist_follows uaf ON a.id = uaf.artist_id
WHERE uaf.user_id = $1
ORDER BY uaf.created_at DESC
LIMIT $2 OFFSET $3
`

type ListFollowingArtistsParams struct {
	UserID uuid.UUID
	Limit  int32
	Offset int32
}

func (q *Queries) ListFollowingArtists(ctx context.Context, arg ListFollowingArtistsParams) ([]Artist, error) {
	rows, err := q.db.QueryContext(ctx, listFollowingArtists, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Artist
	for rows.Next() {
		var i Artist
		if err := rows.Scan(
			&i.ID,
			&i.OfficialName,
			&i.Hiragana,
			&i.Gender,
			&i.ProfileImageUrl,
			&i.BirthDate,
			&i.DebutDate,
			&i.RatingSum,
			&i.RatingCount,
			&i.Status,
			&i.AuthorID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unfollowArtist = `-- name: UnfollowArtist :exec
DELETE FROM user_artist_follows
WHERE user_id = $1 AND artist_id = $2
`

type UnfollowArtistParams struct {
	UserID   uuid.UUID
	ArtistID uuid.UUID
}

func (q *Queries) UnfollowArtist(ctx context.Context, arg UnfollowArtistParams) error {
	_, err := q.db.ExecContext(ctx, unfollowArtist, arg.UserID, arg.ArtistID)
	return err
}

const updateLastArtistFeedCheckedAt = `-- name: UpdateLastArtistFeedCheckedAt :exec
UPDATE users
SET last_artist_feed_checked_at = NOW()
WHERE id = $1
`

func (q *Queries) UpdateLastArtistFeedCheckedAt(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, updateLastArtistFeedCheckedAt, id)
	return err
}
