// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: event_history.sql

package repository

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const createEventHistory = `-- name: CreateEventHistory :one
INSERT INTO event_histories (event_id, editor_id, snapshot)
VALUES ($1, $2, $3)
RETURNING id, event_id, editor_id, snapshot, report_count, status, created_at
`

type CreateEventHistoryParams struct {
	EventID  uuid.UUID
	EditorID uuid.NullUUID
	Snapshot json.RawMessage
}

func (q *Queries) CreateEventHistory(ctx context.Context, arg CreateEventHistoryParams) (EventHistory, error) {
	row := q.db.QueryRowContext(ctx, createEventHistory, arg.EventID, arg.EditorID, arg.Snapshot)
	var i EventHistory
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.EditorID,
		&i.Snapshot,
		&i.ReportCount,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const incrementHistoryReportCount = `-- name: IncrementHistoryReportCount :exec
UPDATE event_histories
SET report_count = report_count + 1
WHERE id = $1
`

func (q *Queries) IncrementHistoryReportCount(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, incrementHistoryReportCount, id)
	return err
}

const listEventHistories = `-- name: ListEventHistories :many
SELECT id, event_id, editor_id, snapshot, report_count, status, created_at FROM event_histories
WHERE event_id = $2
    AND ($3::timestamptz IS NULL OR created_at < $3)
ORDER BY created_at DESC
LIMIT $1
`

type ListEventHistoriesParams struct {
	Limit           int32
	EventID         uuid.UUID
	CursorCreatedAt time.Time
}

func (q *Queries) ListEventHistories(ctx context.Context, arg ListEventHistoriesParams) ([]EventHistory, error) {
	rows, err := q.db.QueryContext(ctx, listEventHistories, arg.Limit, arg.EventID, arg.CursorCreatedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EventHistory
	for rows.Next() {
		var i EventHistory
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.EditorID,
			&i.Snapshot,
			&i.ReportCount,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reportHistory = `-- name: ReportHistory :exec
INSERT INTO history_reports (user_id, history_id)
VALUES ($1, $2) ON CONFLICT DO NOTHING
`

type ReportHistoryParams struct {
	UserID    uuid.UUID
	HistoryID uuid.UUID
}

func (q *Queries) ReportHistory(ctx context.Context, arg ReportHistoryParams) error {
	_, err := q.db.ExecContext(ctx, reportHistory, arg.UserID, arg.HistoryID)
	return err
}

const updateHistoryStatus = `-- name: UpdateHistoryStatus :exec
UPDATE event_histories
SET status = $2
WHERE id = $1
`

type UpdateHistoryStatusParams struct {
	ID     uuid.UUID
	Status string
}

func (q *Queries) UpdateHistoryStatus(ctx context.Context, arg UpdateHistoryStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateHistoryStatus, arg.ID, arg.Status)
	return err
}
