// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: event_thread.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const cancelRecommendThread = `-- name: CancelRecommendThread :exec
DELETE FROM thread_recommendations
WHERE user_id = $1 AND thread_id = $2
`

type CancelRecommendThreadParams struct {
	UserID   uuid.UUID
	ThreadID uuid.UUID
}

func (q *Queries) CancelRecommendThread(ctx context.Context, arg CancelRecommendThreadParams) error {
	_, err := q.db.ExecContext(ctx, cancelRecommendThread, arg.UserID, arg.ThreadID)
	return err
}

const createEventThread = `-- name: CreateEventThread :one
INSERT INTO event_threads (event_id, author_id, content)
VALUES ($1, $2, $3)
RETURNING id, event_id, author_id, content, recommend_count, created_at, updated_at
`

type CreateEventThreadParams struct {
	EventID  uuid.UUID
	AuthorID uuid.NullUUID
	Content  string
}

func (q *Queries) CreateEventThread(ctx context.Context, arg CreateEventThreadParams) (EventThread, error) {
	row := q.db.QueryRowContext(ctx, createEventThread, arg.EventID, arg.AuthorID, arg.Content)
	var i EventThread
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.AuthorID,
		&i.Content,
		&i.RecommendCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const incrementThreadRecommend = `-- name: IncrementThreadRecommend :exec
UPDATE event_threads
SET recommend_count = recommend_count + $1
WHERE id = $2
`

type IncrementThreadRecommendParams struct {
	Amount int32
	ID     uuid.UUID
}

func (q *Queries) IncrementThreadRecommend(ctx context.Context, arg IncrementThreadRecommendParams) error {
	_, err := q.db.ExecContext(ctx, incrementThreadRecommend, arg.Amount, arg.ID)
	return err
}

const listEventThreads = `-- name: ListEventThreads :many
SELECT id, event_id, author_id, content, recommend_count, created_at, updated_at FROM event_threads
WHERE event_id = $2
    AND ($3::int IS NULL OR recommend_count < $3)
ORDER BY recommend_count DESC, id ASC
LIMIT $1
`

type ListEventThreadsParams struct {
	Limit           int32
	EventID         uuid.UUID
	CursorRecommend int32
}

func (q *Queries) ListEventThreads(ctx context.Context, arg ListEventThreadsParams) ([]EventThread, error) {
	rows, err := q.db.QueryContext(ctx, listEventThreads, arg.Limit, arg.EventID, arg.CursorRecommend)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EventThread
	for rows.Next() {
		var i EventThread
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.AuthorID,
			&i.Content,
			&i.RecommendCount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recommendThread = `-- name: RecommendThread :exec
INSERT INTO thread_recommendations (user_id, thread_id)
VALUES ($1, $2) ON CONFLICT DO NOTHING
`

type RecommendThreadParams struct {
	UserID   uuid.UUID
	ThreadID uuid.UUID
}

func (q *Queries) RecommendThread(ctx context.Context, arg RecommendThreadParams) error {
	_, err := q.db.ExecContext(ctx, recommendThread, arg.UserID, arg.ThreadID)
	return err
}
