// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: event.sql

package repository

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const addArtistToEvent = `-- name: AddArtistToEvent :exec
INSERT INTO event_artists (event_id, artist_id)
VALUES ($1, $2) ON CONFLICT DO NOTHING
`

type AddArtistToEventParams struct {
	EventID  uuid.UUID
	ArtistID uuid.UUID
}

func (q *Queries) AddArtistToEvent(ctx context.Context, arg AddArtistToEventParams) error {
	_, err := q.db.ExecContext(ctx, addArtistToEvent, arg.EventID, arg.ArtistID)
	return err
}

const clearArtistsFromEvent = `-- name: ClearArtistsFromEvent :exec
DELETE FROM event_artists
WHERE event_id = $1
`

func (q *Queries) ClearArtistsFromEvent(ctx context.Context, eventID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, clearArtistsFromEvent, eventID)
	return err
}

const createEvent = `-- name: CreateEvent :one
INSERT INTO events (title, venue_id, opening_time, start_time, end_time, related_links, poster_image_url, status, author_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, title, venue_id, opening_time, start_time, end_time, related_links, poster_image_url, rating_sum, rating_count, status, author_id, created_at, updated_at
`

type CreateEventParams struct {
	Title          string
	VenueID        uuid.NullUUID
	OpeningTime    sql.NullTime
	StartTime      time.Time
	EndTime        time.Time
	RelatedLinks   []string
	PosterImageUrl sql.NullString
	Status         string
	AuthorID       uuid.NullUUID
}

func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error) {
	row := q.db.QueryRowContext(ctx, createEvent,
		arg.Title,
		arg.VenueID,
		arg.OpeningTime,
		arg.StartTime,
		arg.EndTime,
		pq.Array(arg.RelatedLinks),
		arg.PosterImageUrl,
		arg.Status,
		arg.AuthorID,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.VenueID,
		&i.OpeningTime,
		&i.StartTime,
		&i.EndTime,
		pq.Array(&i.RelatedLinks),
		&i.PosterImageUrl,
		&i.RatingSum,
		&i.RatingCount,
		&i.Status,
		&i.AuthorID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteUserEventAction = `-- name: DeleteUserEventAction :exec
DELETE FROM event_user_actions
WHERE user_id = $1 AND event_id = $2
`

type DeleteUserEventActionParams struct {
	UserID  uuid.UUID
	EventID uuid.UUID
}

func (q *Queries) DeleteUserEventAction(ctx context.Context, arg DeleteUserEventActionParams) error {
	_, err := q.db.ExecContext(ctx, deleteUserEventAction, arg.UserID, arg.EventID)
	return err
}

const getArtistsForEvent = `-- name: GetArtistsForEvent :many
SELECT a.id, a.official_name, a.hiragana, a.gender, a.profile_image_url, a.birth_date, a.debut_date, a.rating_sum, a.rating_count, a.status, a.author_id, a.created_at, a.updated_at FROM artists a
JOIN event_artists ea ON a.id = ea.artist_id
WHERE ea.event_id = $1
`

func (q *Queries) GetArtistsForEvent(ctx context.Context, eventID uuid.UUID) ([]Artist, error) {
	rows, err := q.db.QueryContext(ctx, getArtistsForEvent, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Artist
	for rows.Next() {
		var i Artist
		if err := rows.Scan(
			&i.ID,
			&i.OfficialName,
			&i.Hiragana,
			&i.Gender,
			&i.ProfileImageUrl,
			&i.BirthDate,
			&i.DebutDate,
			&i.RatingSum,
			&i.RatingCount,
			&i.Status,
			&i.AuthorID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEvent = `-- name: GetEvent :one
SELECT id, title, venue_id, opening_time, start_time, end_time, related_links, poster_image_url, rating_sum, rating_count, status, author_id, created_at, updated_at FROM events
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetEvent(ctx context.Context, id uuid.UUID) (Event, error) {
	row := q.db.QueryRowContext(ctx, getEvent, id)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.VenueID,
		&i.OpeningTime,
		&i.StartTime,
		&i.EndTime,
		pq.Array(&i.RelatedLinks),
		&i.PosterImageUrl,
		&i.RatingSum,
		&i.RatingCount,
		&i.Status,
		&i.AuthorID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEventAttendees = `-- name: GetEventAttendees :many
SELECT u.id, u.email, u.display_name, u.created_at
FROM users u
JOIN event_user_actions eua ON u.id = eua.user_id
WHERE eua.event_id = $1 AND eua.status = 2
  AND NOT EXISTS (
      SELECT 1 FROM user_blocks ub
      WHERE (ub.blocker_id = $2 AND ub.blocked_id = u.id)
         OR (ub.blocker_id = u.id AND ub.blocked_id = $2)
  )
ORDER BY u.created_at DESC
LIMIT $3 OFFSET $4
`

type GetEventAttendeesParams struct {
	EventID   uuid.UUID
	BlockerID uuid.UUID
	Limit     int32
	Offset    int32
}

type GetEventAttendeesRow struct {
	ID          uuid.UUID
	Email       sql.NullString
	DisplayName string
	CreatedAt   time.Time
}

func (q *Queries) GetEventAttendees(ctx context.Context, arg GetEventAttendeesParams) ([]GetEventAttendeesRow, error) {
	rows, err := q.db.QueryContext(ctx, getEventAttendees,
		arg.EventID,
		arg.BlockerID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetEventAttendeesRow
	for rows.Next() {
		var i GetEventAttendeesRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.DisplayName,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserEventAction = `-- name: GetUserEventAction :one
SELECT status FROM event_user_actions
WHERE user_id = $1 AND event_id = $2 LIMIT 1
`

type GetUserEventActionParams struct {
	UserID  uuid.UUID
	EventID uuid.UUID
}

func (q *Queries) GetUserEventAction(ctx context.Context, arg GetUserEventActionParams) (int32, error) {
	row := q.db.QueryRowContext(ctx, getUserEventAction, arg.UserID, arg.EventID)
	var status int32
	err := row.Scan(&status)
	return status, err
}

const getUserRatingForEvent = `-- name: GetUserRatingForEvent :one
SELECT user_id, event_id, score FROM user_event_ratings
WHERE user_id = $1 AND event_id = $2 LIMIT 1
`

type GetUserRatingForEventParams struct {
	UserID  uuid.UUID
	EventID uuid.UUID
}

func (q *Queries) GetUserRatingForEvent(ctx context.Context, arg GetUserRatingForEventParams) (UserEventRating, error) {
	row := q.db.QueryRowContext(ctx, getUserRatingForEvent, arg.UserID, arg.EventID)
	var i UserEventRating
	err := row.Scan(&i.UserID, &i.EventID, &i.Score)
	return i, err
}

const listEvents = `-- name: ListEvents :many
SELECT id, title, venue_id, opening_time, start_time, end_time, related_links, poster_image_url, rating_sum, rating_count, status, author_id, created_at, updated_at FROM events
WHERE 
    start_time >= $2
    AND start_time <= $3
    AND ($4::uuid IS NULL OR venue_id = $4)
    AND ($5::timestamptz IS NULL OR start_time > $5)
ORDER BY start_time ASC
LIMIT $1
`

type ListEventsParams struct {
	Limit           int32
	StartTimeFrom   time.Time
	StartTimeTo     time.Time
	VenueID         uuid.UUID
	CursorStartTime time.Time
}

func (q *Queries) ListEvents(ctx context.Context, arg ListEventsParams) ([]Event, error) {
	rows, err := q.db.QueryContext(ctx, listEvents,
		arg.Limit,
		arg.StartTimeFrom,
		arg.StartTimeTo,
		arg.VenueID,
		arg.CursorStartTime,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.VenueID,
			&i.OpeningTime,
			&i.StartTime,
			&i.EndTime,
			pq.Array(&i.RelatedLinks),
			&i.PosterImageUrl,
			&i.RatingSum,
			&i.RatingCount,
			&i.Status,
			&i.AuthorID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserEventActions = `-- name: ListUserEventActions :many
SELECT user_id, event_id, status FROM event_user_actions
WHERE user_id = $1
ORDER BY event_id
`

func (q *Queries) ListUserEventActions(ctx context.Context, userID uuid.UUID) ([]EventUserAction, error) {
	rows, err := q.db.QueryContext(ctx, listUserEventActions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EventUserAction
	for rows.Next() {
		var i EventUserAction
		if err := rows.Scan(&i.UserID, &i.EventID, &i.Status); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rateEvent = `-- name: RateEvent :exec
INSERT INTO user_event_ratings (user_id, event_id, score)
VALUES ($1, $2, $3)
ON CONFLICT (user_id, event_id) DO UPDATE SET score = EXCLUDED.score
`

type RateEventParams struct {
	UserID  uuid.UUID
	EventID uuid.UUID
	Score   int32
}

func (q *Queries) RateEvent(ctx context.Context, arg RateEventParams) error {
	_, err := q.db.ExecContext(ctx, rateEvent, arg.UserID, arg.EventID, arg.Score)
	return err
}

const updateEvent = `-- name: UpdateEvent :one
UPDATE events
SET title = COALESCE($1, title),
    venue_id = COALESCE($2, venue_id),
    opening_time = COALESCE($3, opening_time),
    start_time = COALESCE($4, start_time),
    end_time = COALESCE($5, end_time),
    related_links = COALESCE($6, related_links),
    poster_image_url = COALESCE($7, poster_image_url),
    status = COALESCE($8, status),
    updated_at = NOW()
WHERE id = $9
RETURNING id, title, venue_id, opening_time, start_time, end_time, related_links, poster_image_url, rating_sum, rating_count, status, author_id, created_at, updated_at
`

type UpdateEventParams struct {
	Title          sql.NullString
	VenueID        uuid.NullUUID
	OpeningTime    sql.NullTime
	StartTime      sql.NullTime
	EndTime        sql.NullTime
	RelatedLinks   []string
	PosterImageUrl sql.NullString
	Status         sql.NullString
	ID             uuid.UUID
}

func (q *Queries) UpdateEvent(ctx context.Context, arg UpdateEventParams) (Event, error) {
	row := q.db.QueryRowContext(ctx, updateEvent,
		arg.Title,
		arg.VenueID,
		arg.OpeningTime,
		arg.StartTime,
		arg.EndTime,
		pq.Array(arg.RelatedLinks),
		arg.PosterImageUrl,
		arg.Status,
		arg.ID,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.VenueID,
		&i.OpeningTime,
		&i.StartTime,
		&i.EndTime,
		pq.Array(&i.RelatedLinks),
		&i.PosterImageUrl,
		&i.RatingSum,
		&i.RatingCount,
		&i.Status,
		&i.AuthorID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateEventRating = `-- name: UpdateEventRating :exec
UPDATE events
SET rating_sum = rating_sum + $1,
    rating_count = rating_count + $2
WHERE id = $3
`

type UpdateEventRatingParams struct {
	ScoreDelta float64
	CountDelta int32
	ID         uuid.UUID
}

func (q *Queries) UpdateEventRating(ctx context.Context, arg UpdateEventRatingParams) error {
	_, err := q.db.ExecContext(ctx, updateEventRating, arg.ScoreDelta, arg.CountDelta, arg.ID)
	return err
}

const upsertUserEventAction = `-- name: UpsertUserEventAction :exec
INSERT INTO event_user_actions (user_id, event_id, status)
VALUES ($1, $2, $3)
ON CONFLICT (user_id, event_id)
DO UPDATE SET status = EXCLUDED.status
`

type UpsertUserEventActionParams struct {
	UserID  uuid.UUID
	EventID uuid.UUID
	Status  int32
}

func (q *Queries) UpsertUserEventAction(ctx context.Context, arg UpsertUserEventActionParams) error {
	_, err := q.db.ExecContext(ctx, upsertUserEventAction, arg.UserID, arg.EventID, arg.Status)
	return err
}
