// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: event.sql

package repository

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const addArtistToEvent = `-- name: AddArtistToEvent :exec
INSERT INTO event_artists (event_id, artist_id)
VALUES ($1, $2) ON CONFLICT DO NOTHING
`

type AddArtistToEventParams struct {
	EventID  uuid.UUID
	ArtistID uuid.UUID
}

func (q *Queries) AddArtistToEvent(ctx context.Context, arg AddArtistToEventParams) error {
	_, err := q.db.ExecContext(ctx, addArtistToEvent, arg.EventID, arg.ArtistID)
	return err
}

const attendEvent = `-- name: AttendEvent :exec
INSERT INTO event_attendances (user_id, event_id)
VALUES ($1, $2) ON CONFLICT DO NOTHING
`

type AttendEventParams struct {
	UserID  uuid.UUID
	EventID uuid.UUID
}

func (q *Queries) AttendEvent(ctx context.Context, arg AttendEventParams) error {
	_, err := q.db.ExecContext(ctx, attendEvent, arg.UserID, arg.EventID)
	return err
}

const cancelAttendance = `-- name: CancelAttendance :exec
DELETE FROM event_attendances
WHERE user_id = $1 AND event_id = $2
`

type CancelAttendanceParams struct {
	UserID  uuid.UUID
	EventID uuid.UUID
}

func (q *Queries) CancelAttendance(ctx context.Context, arg CancelAttendanceParams) error {
	_, err := q.db.ExecContext(ctx, cancelAttendance, arg.UserID, arg.EventID)
	return err
}

const clearArtistsFromEvent = `-- name: ClearArtistsFromEvent :exec
DELETE FROM event_artists
WHERE event_id = $1
`

func (q *Queries) ClearArtistsFromEvent(ctx context.Context, eventID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, clearArtistsFromEvent, eventID)
	return err
}

const createEvent = `-- name: CreateEvent :one
INSERT INTO events (title, venue_id, opening_time, start_time, end_time, related_links, poster_image_url, status, author_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, title, venue_id, opening_time, start_time, end_time, related_links, poster_image_url, rating_sum, rating_count, status, author_id, created_at, updated_at
`

type CreateEventParams struct {
	Title          string
	VenueID        uuid.UUID
	OpeningTime    sql.NullTime
	StartTime      time.Time
	EndTime        time.Time
	RelatedLinks   []string
	PosterImageUrl sql.NullString
	Status         string
	AuthorID       uuid.NullUUID
}

func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error) {
	row := q.db.QueryRowContext(ctx, createEvent,
		arg.Title,
		arg.VenueID,
		arg.OpeningTime,
		arg.StartTime,
		arg.EndTime,
		pq.Array(arg.RelatedLinks),
		arg.PosterImageUrl,
		arg.Status,
		arg.AuthorID,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.VenueID,
		&i.OpeningTime,
		&i.StartTime,
		&i.EndTime,
		pq.Array(&i.RelatedLinks),
		&i.PosterImageUrl,
		&i.RatingSum,
		&i.RatingCount,
		&i.Status,
		&i.AuthorID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getArtistsForEvent = `-- name: GetArtistsForEvent :many
SELECT a.id, a.official_name, a.hiragana, a.gender, a.profile_image_url, a.birth_date, a.debut_date, a.rating_sum, a.rating_count, a.status, a.author_id, a.created_at, a.updated_at FROM artists a
JOIN event_artists ea ON a.id = ea.artist_id
WHERE ea.event_id = $1
`

func (q *Queries) GetArtistsForEvent(ctx context.Context, eventID uuid.UUID) ([]Artist, error) {
	rows, err := q.db.QueryContext(ctx, getArtistsForEvent, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Artist
	for rows.Next() {
		var i Artist
		if err := rows.Scan(
			&i.ID,
			&i.OfficialName,
			&i.Hiragana,
			&i.Gender,
			&i.ProfileImageUrl,
			&i.BirthDate,
			&i.DebutDate,
			&i.RatingSum,
			&i.RatingCount,
			&i.Status,
			&i.AuthorID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEvent = `-- name: GetEvent :one
SELECT id, title, venue_id, opening_time, start_time, end_time, related_links, poster_image_url, rating_sum, rating_count, status, author_id, created_at, updated_at FROM events
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetEvent(ctx context.Context, id uuid.UUID) (Event, error) {
	row := q.db.QueryRowContext(ctx, getEvent, id)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.VenueID,
		&i.OpeningTime,
		&i.StartTime,
		&i.EndTime,
		pq.Array(&i.RelatedLinks),
		&i.PosterImageUrl,
		&i.RatingSum,
		&i.RatingCount,
		&i.Status,
		&i.AuthorID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserRatingForEvent = `-- name: GetUserRatingForEvent :one
SELECT user_id, event_id, score, created_at, updated_at FROM user_event_ratings
WHERE user_id = $1 AND event_id = $2 LIMIT 1
`

type GetUserRatingForEventParams struct {
	UserID  uuid.UUID
	EventID uuid.UUID
}

func (q *Queries) GetUserRatingForEvent(ctx context.Context, arg GetUserRatingForEventParams) (UserEventRating, error) {
	row := q.db.QueryRowContext(ctx, getUserRatingForEvent, arg.UserID, arg.EventID)
	var i UserEventRating
	err := row.Scan(
		&i.UserID,
		&i.EventID,
		&i.Score,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const hasUserAttended = `-- name: HasUserAttended :one
SELECT EXISTS(
    SELECT 1 FROM event_attendances
    WHERE user_id = $1 AND event_id = $2
)
`

type HasUserAttendedParams struct {
	UserID  uuid.UUID
	EventID uuid.UUID
}

func (q *Queries) HasUserAttended(ctx context.Context, arg HasUserAttendedParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, hasUserAttended, arg.UserID, arg.EventID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listEvents = `-- name: ListEvents :many
SELECT id, title, venue_id, opening_time, start_time, end_time, related_links, poster_image_url, rating_sum, rating_count, status, author_id, created_at, updated_at FROM events
WHERE 
    start_time >= $2
    AND start_time <= $3
    AND ($4::uuid IS NULL OR venue_id = $4)
    AND ($5::timestamptz IS NULL OR start_time > $5)
ORDER BY start_time ASC
LIMIT $1
`

type ListEventsParams struct {
	Limit           int32
	StartTimeFrom   time.Time
	StartTimeTo     time.Time
	VenueID         uuid.UUID
	CursorStartTime time.Time
}

func (q *Queries) ListEvents(ctx context.Context, arg ListEventsParams) ([]Event, error) {
	rows, err := q.db.QueryContext(ctx, listEvents,
		arg.Limit,
		arg.StartTimeFrom,
		arg.StartTimeTo,
		arg.VenueID,
		arg.CursorStartTime,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.VenueID,
			&i.OpeningTime,
			&i.StartTime,
			&i.EndTime,
			pq.Array(&i.RelatedLinks),
			&i.PosterImageUrl,
			&i.RatingSum,
			&i.RatingCount,
			&i.Status,
			&i.AuthorID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rateEvent = `-- name: RateEvent :exec
INSERT INTO user_event_ratings (user_id, event_id, score)
VALUES ($1, $2, $3)
ON CONFLICT (user_id, event_id) DO UPDATE SET score = EXCLUDED.score, updated_at = NOW()
`

type RateEventParams struct {
	UserID  uuid.UUID
	EventID uuid.UUID
	Score   int32
}

func (q *Queries) RateEvent(ctx context.Context, arg RateEventParams) error {
	_, err := q.db.ExecContext(ctx, rateEvent, arg.UserID, arg.EventID, arg.Score)
	return err
}

const updateEvent = `-- name: UpdateEvent :one
UPDATE events
SET title = COALESCE($1, title),
    venue_id = COALESCE($2, venue_id),
    opening_time = COALESCE($3, opening_time),
    start_time = COALESCE($4, start_time),
    end_time = COALESCE($5, end_time),
    related_links = COALESCE($6, related_links),
    poster_image_url = COALESCE($7, poster_image_url),
    status = COALESCE($8, status),
    updated_at = NOW()
WHERE id = $9
RETURNING id, title, venue_id, opening_time, start_time, end_time, related_links, poster_image_url, rating_sum, rating_count, status, author_id, created_at, updated_at
`

type UpdateEventParams struct {
	Title          sql.NullString
	VenueID        uuid.NullUUID
	OpeningTime    sql.NullTime
	StartTime      sql.NullTime
	EndTime        sql.NullTime
	RelatedLinks   []string
	PosterImageUrl sql.NullString
	Status         sql.NullString
	ID             uuid.UUID
}

func (q *Queries) UpdateEvent(ctx context.Context, arg UpdateEventParams) (Event, error) {
	row := q.db.QueryRowContext(ctx, updateEvent,
		arg.Title,
		arg.VenueID,
		arg.OpeningTime,
		arg.StartTime,
		arg.EndTime,
		pq.Array(arg.RelatedLinks),
		arg.PosterImageUrl,
		arg.Status,
		arg.ID,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.VenueID,
		&i.OpeningTime,
		&i.StartTime,
		&i.EndTime,
		pq.Array(&i.RelatedLinks),
		&i.PosterImageUrl,
		&i.RatingSum,
		&i.RatingCount,
		&i.Status,
		&i.AuthorID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateEventRating = `-- name: UpdateEventRating :exec
UPDATE events
SET rating_sum = rating_sum + $1,
    rating_count = rating_count + $2
WHERE id = $3
`

type UpdateEventRatingParams struct {
	ScoreDelta float64
	CountDelta int32
	ID         uuid.UUID
}

func (q *Queries) UpdateEventRating(ctx context.Context, arg UpdateEventRatingParams) error {
	_, err := q.db.ExecContext(ctx, updateEventRating, arg.ScoreDelta, arg.CountDelta, arg.ID)
	return err
}
