// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repository

import (
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

type Artist struct {
	ID              uuid.UUID
	OfficialName    string
	Hiragana        sql.NullString
	Gender          string
	ProfileImageUrl sql.NullString
	BirthDate       sql.NullTime
	DebutDate       sql.NullTime
	RatingSum       float64
	RatingCount     int32
	Status          string
	AuthorID        uuid.NullUUID
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

type Event struct {
	ID             uuid.UUID
	Title          string
	VenueID        uuid.UUID
	OpeningTime    sql.NullTime
	StartTime      time.Time
	EndTime        time.Time
	RelatedLinks   []string
	PosterImageUrl sql.NullString
	RatingSum      float64
	RatingCount    int32
	Status         string
	AuthorID       uuid.NullUUID
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type EventArtist struct {
	EventID  uuid.UUID
	ArtistID uuid.UUID
}

type EventAttendance struct {
	UserID    uuid.UUID
	EventID   uuid.UUID
	CreatedAt time.Time
}

type EventHistory struct {
	ID          uuid.UUID
	EventID     uuid.UUID
	EditorID    uuid.NullUUID
	Snapshot    json.RawMessage
	ReportCount int32
	Status      string
	CreatedAt   time.Time
}

type EventThread struct {
	ID             uuid.UUID
	EventID        uuid.UUID
	AuthorID       uuid.NullUUID
	Content        string
	RecommendCount int32
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type HistoryReport struct {
	UserID    uuid.UUID
	HistoryID uuid.UUID
	CreatedAt time.Time
}

type ThreadRecommendation struct {
	UserID    uuid.UUID
	ThreadID  uuid.UUID
	CreatedAt time.Time
}

type User struct {
	ID           uuid.UUID
	Email        sql.NullString
	DisplayName  string
	PasswordHash sql.NullString
	GoogleID     sql.NullString
	IsBanned     bool
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type UserEventRating struct {
	UserID    uuid.UUID
	EventID   uuid.UUID
	Score     int32
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Venue struct {
	ID           uuid.UUID
	OfficialName string
	GoogleMapID  string
	Address      string
	Latitude     float64
	Longitude    float64
	RelatedLinks []string
	Capacity     sql.NullInt32
	RatingSum    float64
	RatingCount  int32
	Status       string
	AuthorID     uuid.NullUUID
	CreatedAt    time.Time
	UpdatedAt    time.Time
}
