// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_social.sql

package repository

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const blockUser = `-- name: BlockUser :exec
INSERT INTO user_blocks (blocker_id, blocked_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type BlockUserParams struct {
	BlockerID uuid.UUID
	BlockedID uuid.UUID
}

func (q *Queries) BlockUser(ctx context.Context, arg BlockUserParams) error {
	_, err := q.db.ExecContext(ctx, blockUser, arg.BlockerID, arg.BlockedID)
	return err
}

const checkBlockExists = `-- name: CheckBlockExists :one
SELECT EXISTS (
    SELECT 1 FROM user_blocks
    WHERE (blocker_id = $1 AND blocked_id = $2)
       OR (blocker_id = $2 AND blocked_id = $1)
)
`

type CheckBlockExistsParams struct {
	BlockerID uuid.UUID
	BlockedID uuid.UUID
}

func (q *Queries) CheckBlockExists(ctx context.Context, arg CheckBlockExistsParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, checkBlockExists, arg.BlockerID, arg.BlockedID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const deleteMutualFollows = `-- name: DeleteMutualFollows :exec
DELETE FROM user_follows
WHERE (follower_id = $1 AND followee_id = $2)
   OR (follower_id = $2 AND followee_id = $1)
`

type DeleteMutualFollowsParams struct {
	FollowerID uuid.UUID
	FolloweeID uuid.UUID
}

func (q *Queries) DeleteMutualFollows(ctx context.Context, arg DeleteMutualFollowsParams) error {
	_, err := q.db.ExecContext(ctx, deleteMutualFollows, arg.FollowerID, arg.FolloweeID)
	return err
}

const followUser = `-- name: FollowUser :exec
INSERT INTO user_follows (follower_id, followee_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type FollowUserParams struct {
	FollowerID uuid.UUID
	FolloweeID uuid.UUID
}

func (q *Queries) FollowUser(ctx context.Context, arg FollowUserParams) error {
	_, err := q.db.ExecContext(ctx, followUser, arg.FollowerID, arg.FolloweeID)
	return err
}

const listFollowers = `-- name: ListFollowers :many
SELECT u.id, u.email, u.display_name, u.created_at
FROM users u
JOIN user_follows uf ON u.id = uf.follower_id
WHERE uf.followee_id = $1
ORDER BY uf.created_at DESC
LIMIT $2 OFFSET $3
`

type ListFollowersParams struct {
	FolloweeID uuid.UUID
	Limit      int32
	Offset     int32
}

type ListFollowersRow struct {
	ID          uuid.UUID
	Email       sql.NullString
	DisplayName string
	CreatedAt   time.Time
}

func (q *Queries) ListFollowers(ctx context.Context, arg ListFollowersParams) ([]ListFollowersRow, error) {
	rows, err := q.db.QueryContext(ctx, listFollowers, arg.FolloweeID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFollowersRow
	for rows.Next() {
		var i ListFollowersRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.DisplayName,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFollowing = `-- name: ListFollowing :many
SELECT u.id, u.email, u.display_name, u.created_at
FROM users u
JOIN user_follows uf ON u.id = uf.followee_id
WHERE uf.follower_id = $1
ORDER BY uf.created_at DESC
LIMIT $2 OFFSET $3
`

type ListFollowingParams struct {
	FollowerID uuid.UUID
	Limit      int32
	Offset     int32
}

type ListFollowingRow struct {
	ID          uuid.UUID
	Email       sql.NullString
	DisplayName string
	CreatedAt   time.Time
}

func (q *Queries) ListFollowing(ctx context.Context, arg ListFollowingParams) ([]ListFollowingRow, error) {
	rows, err := q.db.QueryContext(ctx, listFollowing, arg.FollowerID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFollowingRow
	for rows.Next() {
		var i ListFollowingRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.DisplayName,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFollowingEvents = `-- name: ListFollowingEvents :many
SELECT DISTINCT e.id, e.title, e.venue_id, e.opening_time, e.start_time, e.end_time, e.related_links, e.poster_image_url, e.rating_sum, e.rating_count, e.status, e.author_id, e.created_at, e.updated_at
FROM events e
JOIN event_user_actions eua ON e.id = eua.event_id
JOIN user_follows uf ON eua.user_id = uf.followee_id
WHERE uf.follower_id = $1 AND eua.status = 2
ORDER BY e.start_time DESC
LIMIT $2 OFFSET $3
`

type ListFollowingEventsParams struct {
	FollowerID uuid.UUID
	Limit      int32
	Offset     int32
}

func (q *Queries) ListFollowingEvents(ctx context.Context, arg ListFollowingEventsParams) ([]Event, error) {
	rows, err := q.db.QueryContext(ctx, listFollowingEvents, arg.FollowerID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.VenueID,
			&i.OpeningTime,
			&i.StartTime,
			&i.EndTime,
			pq.Array(&i.RelatedLinks),
			&i.PosterImageUrl,
			&i.RatingSum,
			&i.RatingCount,
			&i.Status,
			&i.AuthorID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unblockUser = `-- name: UnblockUser :exec
DELETE FROM user_blocks
WHERE blocker_id = $1 AND blocked_id = $2
`

type UnblockUserParams struct {
	BlockerID uuid.UUID
	BlockedID uuid.UUID
}

func (q *Queries) UnblockUser(ctx context.Context, arg UnblockUserParams) error {
	_, err := q.db.ExecContext(ctx, unblockUser, arg.BlockerID, arg.BlockedID)
	return err
}

const unfollowUser = `-- name: UnfollowUser :exec
DELETE FROM user_follows
WHERE follower_id = $1 AND followee_id = $2
`

type UnfollowUserParams struct {
	FollowerID uuid.UUID
	FolloweeID uuid.UUID
}

func (q *Queries) UnfollowUser(ctx context.Context, arg UnfollowUserParams) error {
	_, err := q.db.ExecContext(ctx, unfollowUser, arg.FollowerID, arg.FolloweeID)
	return err
}
