// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: venue.sql

package repository

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const createVenue = `-- name: CreateVenue :one
INSERT INTO venues (official_name, google_map_id, address, latitude, longitude, related_links, capacity, status, author_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, official_name, google_map_id, address, latitude, longitude, related_links, capacity, rating_sum, rating_count, status, author_id, created_at, updated_at
`

type CreateVenueParams struct {
	OfficialName string
	GoogleMapID  string
	Address      string
	Latitude     float64
	Longitude    float64
	RelatedLinks []string
	Capacity     sql.NullInt32
	Status       string
	AuthorID     uuid.NullUUID
}

func (q *Queries) CreateVenue(ctx context.Context, arg CreateVenueParams) (Venue, error) {
	row := q.db.QueryRowContext(ctx, createVenue,
		arg.OfficialName,
		arg.GoogleMapID,
		arg.Address,
		arg.Latitude,
		arg.Longitude,
		pq.Array(arg.RelatedLinks),
		arg.Capacity,
		arg.Status,
		arg.AuthorID,
	)
	var i Venue
	err := row.Scan(
		&i.ID,
		&i.OfficialName,
		&i.GoogleMapID,
		&i.Address,
		&i.Latitude,
		&i.Longitude,
		pq.Array(&i.RelatedLinks),
		&i.Capacity,
		&i.RatingSum,
		&i.RatingCount,
		&i.Status,
		&i.AuthorID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getVenue = `-- name: GetVenue :one
SELECT id, official_name, google_map_id, address, latitude, longitude, related_links, capacity, rating_sum, rating_count, status, author_id, created_at, updated_at FROM venues
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetVenue(ctx context.Context, id uuid.UUID) (Venue, error) {
	row := q.db.QueryRowContext(ctx, getVenue, id)
	var i Venue
	err := row.Scan(
		&i.ID,
		&i.OfficialName,
		&i.GoogleMapID,
		&i.Address,
		&i.Latitude,
		&i.Longitude,
		pq.Array(&i.RelatedLinks),
		&i.Capacity,
		&i.RatingSum,
		&i.RatingCount,
		&i.Status,
		&i.AuthorID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listVenuesByBoundingBox = `-- name: ListVenuesByBoundingBox :many
SELECT id, official_name, google_map_id, address, latitude, longitude, related_links, capacity, rating_sum, rating_count, status, author_id, created_at, updated_at FROM venues
WHERE 
    latitude BETWEEN $2 AND $3
    AND longitude BETWEEN $4 AND $5
    AND ($6::varchar IS NULL OR status = $6)
    AND ($7::uuid IS NULL OR id > $7)
ORDER BY id ASC
LIMIT $1
`

type ListVenuesByBoundingBoxParams struct {
	Limit    int32
	MinLat   float64
	MaxLat   float64
	MinLon   float64
	MaxLon   float64
	Status   string
	CursorID uuid.UUID
}

func (q *Queries) ListVenuesByBoundingBox(ctx context.Context, arg ListVenuesByBoundingBoxParams) ([]Venue, error) {
	rows, err := q.db.QueryContext(ctx, listVenuesByBoundingBox,
		arg.Limit,
		arg.MinLat,
		arg.MaxLat,
		arg.MinLon,
		arg.MaxLon,
		arg.Status,
		arg.CursorID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Venue
	for rows.Next() {
		var i Venue
		if err := rows.Scan(
			&i.ID,
			&i.OfficialName,
			&i.GoogleMapID,
			&i.Address,
			&i.Latitude,
			&i.Longitude,
			pq.Array(&i.RelatedLinks),
			&i.Capacity,
			&i.RatingSum,
			&i.RatingCount,
			&i.Status,
			&i.AuthorID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateVenue = `-- name: UpdateVenue :one
UPDATE venues
SET official_name = COALESCE($1, official_name),
    google_map_id = COALESCE($2, google_map_id),
    address = COALESCE($3, address),
    latitude = COALESCE($4, latitude),
    longitude = COALESCE($5, longitude),
    related_links = COALESCE($6, related_links),
    capacity = COALESCE($7, capacity),
    status = COALESCE($8, status),
    updated_at = NOW()
WHERE id = $9
RETURNING id, official_name, google_map_id, address, latitude, longitude, related_links, capacity, rating_sum, rating_count, status, author_id, created_at, updated_at
`

type UpdateVenueParams struct {
	OfficialName sql.NullString
	GoogleMapID  sql.NullString
	Address      sql.NullString
	Latitude     sql.NullFloat64
	Longitude    sql.NullFloat64
	RelatedLinks []string
	Capacity     sql.NullInt32
	Status       sql.NullString
	ID           uuid.UUID
}

func (q *Queries) UpdateVenue(ctx context.Context, arg UpdateVenueParams) (Venue, error) {
	row := q.db.QueryRowContext(ctx, updateVenue,
		arg.OfficialName,
		arg.GoogleMapID,
		arg.Address,
		arg.Latitude,
		arg.Longitude,
		pq.Array(arg.RelatedLinks),
		arg.Capacity,
		arg.Status,
		arg.ID,
	)
	var i Venue
	err := row.Scan(
		&i.ID,
		&i.OfficialName,
		&i.GoogleMapID,
		&i.Address,
		&i.Latitude,
		&i.Longitude,
		pq.Array(&i.RelatedLinks),
		&i.Capacity,
		&i.RatingSum,
		&i.RatingCount,
		&i.Status,
		&i.AuthorID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateVenueRating = `-- name: UpdateVenueRating :exec
UPDATE venues
SET rating_sum = rating_sum + $1,
    rating_count = rating_count + $2
WHERE id = $3
`

type UpdateVenueRatingParams struct {
	ScoreDelta float64
	CountDelta int32
	ID         uuid.UUID
}

func (q *Queries) UpdateVenueRating(ctx context.Context, arg UpdateVenueRatingParams) error {
	_, err := q.db.ExecContext(ctx, updateVenueRating, arg.ScoreDelta, arg.CountDelta, arg.ID)
	return err
}
