// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: verification.sql

package repository

import (
	"context"
	"time"
)

const createVerificationToken = `-- name: CreateVerificationToken :one
INSERT INTO verification_tokens (email, code, expires_at)
VALUES ($1, $2, $3)
ON CONFLICT (email) DO UPDATE 
SET code = EXCLUDED.code, expires_at = EXCLUDED.expires_at
RETURNING email, code, expires_at
`

type CreateVerificationTokenParams struct {
	Email     string
	Code      string
	ExpiresAt time.Time
}

func (q *Queries) CreateVerificationToken(ctx context.Context, arg CreateVerificationTokenParams) (VerificationToken, error) {
	row := q.db.QueryRowContext(ctx, createVerificationToken, arg.Email, arg.Code, arg.ExpiresAt)
	var i VerificationToken
	err := row.Scan(&i.Email, &i.Code, &i.ExpiresAt)
	return i, err
}

const deleteVerificationToken = `-- name: DeleteVerificationToken :exec
DELETE FROM verification_tokens
WHERE email = $1
`

func (q *Queries) DeleteVerificationToken(ctx context.Context, email string) error {
	_, err := q.db.ExecContext(ctx, deleteVerificationToken, email)
	return err
}

const getVerificationToken = `-- name: GetVerificationToken :one
SELECT email, code, expires_at FROM verification_tokens
WHERE email = $1 AND code = $2
`

type GetVerificationTokenParams struct {
	Email string
	Code  string
}

func (q *Queries) GetVerificationToken(ctx context.Context, arg GetVerificationTokenParams) (VerificationToken, error) {
	row := q.db.QueryRowContext(ctx, getVerificationToken, arg.Email, arg.Code)
	var i VerificationToken
	err := row.Scan(&i.Email, &i.Code, &i.ExpiresAt)
	return i, err
}
