// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: visit.sql

package repository

import (
	"context"
)

const getDailyVisit = `-- name: GetDailyVisit :one
SELECT visit_count
FROM daily_visits
WHERE visit_date = CURRENT_DATE
`

func (q *Queries) GetDailyVisit(ctx context.Context) (int32, error) {
	row := q.db.QueryRowContext(ctx, getDailyVisit)
	var visit_count int32
	err := row.Scan(&visit_count)
	return visit_count, err
}

const incrementDailyVisit = `-- name: IncrementDailyVisit :one
INSERT INTO daily_visits (visit_date, visit_count)
VALUES (CURRENT_DATE, 1)
ON CONFLICT (visit_date)
DO UPDATE SET visit_count = daily_visits.visit_count + 1
RETURNING visit_count
`

func (q *Queries) IncrementDailyVisit(ctx context.Context) (int32, error) {
	row := q.db.QueryRowContext(ctx, incrementDailyVisit)
	var visit_count int32
	err := row.Scan(&visit_count)
	return visit_count, err
}
