"""optimization_and_cleanup

Revision ID: 4feb22b82061
Revises: 5bcb493a5594
Create Date: 2026-04-17 07:09:24.821966

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4feb22b82061'
down_revision: Union[str, Sequence[str], None] = '5bcb493a5594'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_event_histories_event_id'), 'event_histories', ['event_id'], unique=False)
    op.create_index(op.f('ix_event_histories_user_id'), 'event_histories', ['user_id'], unique=False)
    op.create_index(op.f('ix_event_reports_event_id'), 'event_reports', ['event_id'], unique=False)
    op.create_index(op.f('ix_event_reports_reporter_id'), 'event_reports', ['reporter_id'], unique=False)
    op.create_index(op.f('ix_events_created_at'), 'events', ['created_at'], unique=False)
    op.create_index(op.f('ix_events_created_by'), 'events', ['created_by'], unique=False)
    op.create_index('ix_events_date_hidden', 'events', ['event_date', 'is_hidden'], unique=False)
    op.create_index(op.f('ix_events_event_date'), 'events', ['event_date'], unique=False)
    op.create_index(op.f('ix_events_is_hidden'), 'events', ['is_hidden'], unique=False)
    op.create_index(op.f('ix_events_place_id'), 'events', ['place_id'], unique=False)
    op.create_index(op.f('ix_events_updated_by'), 'events', ['updated_by'], unique=False)
    op.drop_index(op.f('ix_performer_aliases_alias'), table_name='performer_aliases')
    op.drop_index(op.f('ix_performer_aliases_normalized_alias'), table_name='performer_aliases')
    op.create_index(op.f('ix_performers_created_at'), 'performers', ['created_at'], unique=False)
    op.drop_column('performers', 'aliases')
    op.drop_index(op.f('ix_place_aliases_alias'), table_name='place_aliases')
    op.drop_index(op.f('ix_place_aliases_normalized_alias'), table_name='place_aliases')
    op.create_index(op.f('ix_places_created_at'), 'places', ['created_at'], unique=False)
    op.drop_column('places', 'aliases')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('places', sa.Column('aliases', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_places_created_at'), table_name='places')
    op.create_index(op.f('ix_place_aliases_normalized_alias'), 'place_aliases', ['normalized_alias'], unique=False)
    op.create_index(op.f('ix_place_aliases_alias'), 'place_aliases', ['alias'], unique=False)
    op.add_column('performers', sa.Column('aliases', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_performers_created_at'), table_name='performers')
    op.create_index(op.f('ix_performer_aliases_normalized_alias'), 'performer_aliases', ['normalized_alias'], unique=False)
    op.create_index(op.f('ix_performer_aliases_alias'), 'performer_aliases', ['alias'], unique=False)
    op.drop_index(op.f('ix_events_updated_by'), table_name='events')
    op.drop_index(op.f('ix_events_place_id'), table_name='events')
    op.drop_index(op.f('ix_events_is_hidden'), table_name='events')
    op.drop_index(op.f('ix_events_event_date'), table_name='events')
    op.drop_index('ix_events_date_hidden', table_name='events')
    op.drop_index(op.f('ix_events_created_by'), table_name='events')
    op.drop_index(op.f('ix_events_created_at'), table_name='events')
    op.drop_index(op.f('ix_event_reports_reporter_id'), table_name='event_reports')
    op.drop_index(op.f('ix_event_reports_event_id'), table_name='event_reports')
    op.drop_index(op.f('ix_event_histories_user_id'), table_name='event_histories')
    op.drop_index(op.f('ix_event_histories_event_id'), table_name='event_histories')
    # ### end Alembic commands ###
