"""normalize_aliases

Revision ID: 5bcb493a5594
Revises: c6226ea7b758
Create Date: 2026-04-09 15:14:21.410825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5bcb493a5594'
down_revision: Union[str, Sequence[str], None] = 'c6226ea7b758'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('performer_aliases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('performer_id', sa.Integer(), nullable=False),
    sa.Column('alias', sa.String(), nullable=False),
    sa.Column('normalized_alias', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['performer_id'], ['performers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_performer_aliases_alias'), 'performer_aliases', ['alias'], unique=False)
    op.create_index('ix_performer_aliases_normalized', 'performer_aliases', ['normalized_alias'], unique=False)
    op.create_index(op.f('ix_performer_aliases_normalized_alias'), 'performer_aliases', ['normalized_alias'], unique=False)
    op.create_index(op.f('ix_performer_aliases_performer_id'), 'performer_aliases', ['performer_id'], unique=False)
    op.create_table('place_aliases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('place_id', sa.Integer(), nullable=False),
    sa.Column('alias', sa.String(), nullable=False),
    sa.Column('normalized_alias', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['place_id'], ['places.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_place_aliases_alias'), 'place_aliases', ['alias'], unique=False)
    op.create_index('ix_place_aliases_normalized', 'place_aliases', ['normalized_alias'], unique=False)
    op.create_index(op.f('ix_place_aliases_normalized_alias'), 'place_aliases', ['normalized_alias'], unique=False)
    op.create_index(op.f('ix_place_aliases_place_id'), 'place_aliases', ['place_id'], unique=False)
    # ### end Alembic commands ###

    # --- Data Migration ---
    import json
    import sys
    import os
    
    # 프로젝트 루트를 경로에 추가하여 유틸리티 사용 가능하게 함
    sys.path.append(os.getcwd())
    try:
        from utils.normalization import normalize_text
    except ImportError:
        # 유틸리티 로드 실패 시 간단한 정규화 함수 정의 (비상용)
        def normalize_text(text):
            if not text: return ""
            return text.lower().replace(" ", "").replace("-", "")

    connection = op.get_bind()

    # 1. Place Aliases Migration
    places = connection.execute(sa.text("SELECT id, aliases FROM places")).fetchall()
    for row in places:
        place_id, aliases_json = row
        if aliases_json:
            try:
                aliases = json.loads(aliases_json)
                for alias in aliases:
                    if alias:
                        connection.execute(
                            sa.text("INSERT INTO place_aliases (place_id, alias, normalized_alias) VALUES (:pid, :a, :na)"),
                            {"pid": place_id, "a": alias, "na": normalize_text(alias)}
                        )
            except Exception as e:
                print(f"Error migrating place {place_id}: {e}")

    # 2. Performer Aliases Migration
    performers = connection.execute(sa.text("SELECT id, aliases FROM performers")).fetchall()
    for row in performers:
        p_id, aliases_json = row
        if aliases_json:
            try:
                aliases = json.loads(aliases_json)
                for alias in aliases:
                    if alias:
                        connection.execute(
                            sa.text("INSERT INTO performer_aliases (performer_id, alias, normalized_alias) VALUES (:pid, :a, :na)"),
                            {"pid": p_id, "a": alias, "na": normalize_text(alias)}
                        )
            except Exception as e:
                print(f"Error migrating performer {p_id}: {e}")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_place_aliases_place_id'), table_name='place_aliases')
    op.drop_index(op.f('ix_place_aliases_normalized_alias'), table_name='place_aliases')
    op.drop_index('ix_place_aliases_normalized', table_name='place_aliases')
    op.drop_index(op.f('ix_place_aliases_alias'), table_name='place_aliases')
    op.drop_table('place_aliases')
    op.drop_index(op.f('ix_performer_aliases_performer_id'), table_name='performer_aliases')
    op.drop_index(op.f('ix_performer_aliases_normalized_alias'), table_name='performer_aliases')
    op.drop_index('ix_performer_aliases_normalized', table_name='performer_aliases')
    op.drop_index(op.f('ix_performer_aliases_alias'), table_name='performer_aliases')
    op.drop_table('performer_aliases')
    # ### end Alembic commands ###
