"""remove performers column from events

Revision ID: c6226ea7b758
Revises: dc83f7ca7d20
Create Date: 2026-04-06 21:10:48.823452

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6226ea7b758'
down_revision: Union[str, Sequence[str], None] = 'dc83f7ca7d20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'performers')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('performers', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
